# -*- coding: utf-8 -*-
"""Generate the Digər məhsullar Excel (Cisco/HP/Aruba/Fortinet/PaloAlto/TP-Link) for the IT Market site.

Sources: "Sayt üçün 24082026_260812_162518 -Diger.docx" + live catalog categories.
- Old price = discounted price + 50 AZN.
- Condition: Yeni (products marked "yeni") / İşlənmiş (all others).
- RU/EN feature columns are for the translation dictionary database.
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

MAIN_NETWORK = "Şəbəkə avadanlıqları"
MAIN_SERVER = "Server"

COND_YENI = "Yeni"
COND_ISLENMIS = "İşlənmiş"

C_NEW = ("Vəziyyəti: Yeni (istifadə olunmamış, orijinal qablaşdırmada)",
         "Состояние: Новый (не использовался, в оригинальной упаковке)",
         "Condition: New (unused, original packaging)")
C_USED = ("Vəziyyəti: İşlənmiş (tam saz, texniki test edilmiş)",
          "Состояние: Б/У (в полном рабочем состоянии, протестировано)",
          "Condition: Used (fully functional, tested)")


def condition_specs(condition):
    return C_NEW if condition == COND_YENI else C_USED


def combine(cond, az, ru, en):
    """Prepend the condition spec line to each language list."""
    c_az, c_ru, c_en = condition_specs(cond)
    return [c_az, *az], [c_ru, *ru], [c_en, *en]


# ---------------------------------------------------------------- products --
# (num, model, barcode, qty, price, main, sub, brand, condition, az, ru, en)
P = []


def add(num, model, barcode, qty, price, main, sub, brand, cond, az, ru, en):
    P.append((num, model, barcode, qty, price, main, sub, brand, cond, *combine(cond, az, ru, en)))


# ============ ACCESS POINT ============
SUB_AP = "Access Point"

add(1, "CISCO AIR CAP702W-A-9", None, 7, 60, MAIN_NETWORK, SUB_AP, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz giriş nöqtəsi (divar rozetkası tipli)",
     "Standart: IEEE 802.11a/b/g/n",
     "Tezlik diapazonları: 2.4 GHz + 5 GHz (ikizolaqlı)",
     "MIMO: 2×2 (hər zolaqda 2 axın)",
     "Maks. simsiz sürət: 300 Mbps (2.4 GHz) / 300 Mbps (5 GHz)",
     "Portlar: 1× Gigabit Ethernet (PoE uplink) + 4× Fast Ethernet (PoE, IP telefonlar üçün)",
     "Güc: IEEE 802.3af PoE",
     "Antena: Daxili",
     "İdarəetmə: Cisco WLAN Controller ilə mərkəzləşdirilmiş"],
    ["Тип: Беспроводная точка доступа (настенного типа)",
     "Стандарт: IEEE 802.11a/b/g/n",
     "Диапазоны: 2.4 ГГц + 5 ГГц (двухдиапазонная)",
     "MIMO: 2×2 (2 потока в каждом диапазоне)",
     "Макс. беспроводная скорость: 300 Мбит/с (2.4 ГГц) / 300 Мбит/с (5 ГГц)",
     "Порты: 1× Gigabit Ethernet (PoE uplink) + 4× Fast Ethernet (PoE для IP-телефонов)",
     "Питание: IEEE 802.3af PoE",
     "Антенна: Встроенная",
     "Управление: Централизованное через Cisco WLAN Controller"],
    ["Type: Wireless access point (wall-plate form factor)",
     "Standard: IEEE 802.11a/b/g/n",
     "Bands: 2.4 GHz + 5 GHz (dual-band)",
     "MIMO: 2×2 (2 streams per band)",
     "Max wireless rate: 300 Mbps (2.4 GHz) / 300 Mbps (5 GHz)",
     "Ports: 1× Gigabit Ethernet (PoE uplink) + 4× Fast Ethernet (PoE for IP phones)",
     "Power: IEEE 802.3af PoE",
     "Antenna: Built-in",
     "Management: Centralized via Cisco WLAN Controller"])

add(2, "CISCO AIR BR1310G-A-K9-R", None, 4, 130, MAIN_NETWORK, SUB_AP, "Cisco", COND_ISLENMIS,
    ["Tip: Xarici simsiz körpü (Wireless Bridge)",
     "Standart: IEEE 802.11g",
     "Tezlik: 2.4 GHz",
     "Maks. sürət: 54 Mbps",
     "Rejimlər: Point-to-Point / Point-to-Multipoint (Root/Non-Root)",
     "Məsafə: Xarici antena ilə 27 km-ə qədər",
     "Port: 1× 10/100 Ethernet",
     "Qoruma: IP65 (hava şəraitinə davamlı)",
     "Güc: PoE (IEEE 802.3af)",
     "İdarəetmə: Console / Telnet / Web"],
    ["Тип: Уличный беспроводной мост (Wireless Bridge)",
     "Стандарт: IEEE 802.11g",
     "Частота: 2.4 ГГц",
     "Макс. скорость: 54 Мбит/с",
     "Режимы: Точка-точка / Точка-многоточка (Root/Non-Root)",
     "Дальность: до 27 км с внешней антенной",
     "Порт: 1× 10/100 Ethernet",
     "Защита: IP65 (устойчив к погодным условиям)",
     "Питание: PoE (IEEE 802.3af)",
     "Управление: Console / Telnet / Web"],
    ["Type: Outdoor wireless bridge",
     "Standard: IEEE 802.11g",
     "Frequency: 2.4 GHz",
     "Max rate: 54 Mbps",
     "Modes: Point-to-Point / Point-to-Multipoint (Root/Non-Root)",
     "Range: up to 27 km with external antenna",
     "Port: 1× 10/100 Ethernet",
     "Protection: IP65 (weatherproof)",
     "Power: PoE (IEEE 802.3af)",
     "Management: Console / Telnet / Web"])

add(3, "CISCO AIR AP1142N-A-K9", None, 1, 70, MAIN_NETWORK, SUB_AP, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz giriş nöqtəsi (daxili)",
     "Standart: IEEE 802.11a/b/g/n",
     "Tezlik: 2.4 GHz + 5 GHz (ikizolaqlı)",
     "MIMO: 2×2 (300 Mbps hər zolaqda)",
     "Antena: Daxili (diversity)",
     "Portlar: 1× 10/100/1000 LAN + 1× 10/100 AUX",
     "Güc: IEEE 802.3af PoE",
     "Rejimlər: Müstəqil (standalone) / Controller (Lightweight)",
     "İdarəetmə: CLI / Web / SNMP"],
    ["Тип: Беспроводная точка доступа (внутренняя)",
     "Стандарт: IEEE 802.11a/b/g/n",
     "Частота: 2.4 ГГц + 5 ГГц (двухдиапазонная)",
     "MIMO: 2×2 (300 Мбит/с в каждом диапазоне)",
     "Антенна: Встроенная (разнесённая)",
     "Порты: 1× 10/100/1000 LAN + 1× 10/100 AUX",
     "Питание: IEEE 802.3af PoE",
     "Режимы: Автономный / Controller (Lightweight)",
     "Управление: CLI / Web / SNMP"],
    ["Type: Wireless access point (indoor)",
     "Standard: IEEE 802.11a/b/g/n",
     "Bands: 2.4 GHz + 5 GHz (dual-band)",
     "MIMO: 2×2 (300 Mbps per band)",
     "Antenna: Built-in (diversity)",
     "Ports: 1× 10/100/1000 LAN + 1× 10/100 AUX",
     "Power: IEEE 802.3af PoE",
     "Modes: Standalone / Controller (Lightweight)",
     "Management: CLI / Web / SNMP"])

_3702 = ([
    "Tip: Simsiz giriş nöqtəsi (daxili, 802.11ac)",
    "Standart: IEEE 802.11ac Wave 1 / a/b/g/n",
    "Tezlik: 2.4 GHz + 5 GHz (ikizolaqlı)",
    "MIMO: 3×3 (5 GHz) + 3×3 (2.4 GHz)",
    "Maks. sürət: 1.3 Gbps (5 GHz) + 450 Mbps (2.4 GHz)",
    "ClientLink 2.0: Köhnə kliyentlərdə performans artımı",
    "Antena: Daxili (integrated)",
    "Port: 1× 10/100/1000 Ethernet (PoE+)",
    "Güc: IEEE 802.3at PoE+ / 802.3af PoE",
    "İdarəetmə: Cisco WLC / Mobility Express",
], [
    "Тип: Беспроводная точка доступа (внутренняя, 802.11ac)",
    "Стандарт: IEEE 802.11ac Wave 1 / a/b/g/n",
    "Частота: 2.4 ГГц + 5 ГГц (двухдиапазонная)",
    "MIMO: 3×3 (5 ГГц) + 3×3 (2.4 ГГц)",
    "Макс. скорость: 1.3 Гбит/с (5 ГГц) + 450 Мбит/с (2.4 ГГц)",
    "ClientLink 2.0: Повышение производительности для старых клиентов",
    "Антенна: Встроенная",
    "Порт: 1× 10/100/1000 Ethernet (PoE+)",
    "Питание: IEEE 802.3at PoE+ / 802.3af PoE",
    "Управление: Cisco WLC / Mobility Express",
], [
    "Type: Wireless access point (indoor, 802.11ac)",
    "Standard: IEEE 802.11ac Wave 1 / a/b/g/n",
    "Bands: 2.4 GHz + 5 GHz (dual-band)",
    "MIMO: 3×3 (5 GHz) + 3×3 (2.4 GHz)",
    "Max rate: 1.3 Gbps (5 GHz) + 450 Mbps (2.4 GHz)",
    "ClientLink 2.0: Performance boost for legacy clients",
    "Antenna: Built-in",
    "Port: 1× 10/100/1000 Ethernet (PoE+)",
    "Power: IEEE 802.3at PoE+ / 802.3af PoE",
    "Management: Cisco WLC / Mobility Express",
])

add(4, "CISCO AIR CAP3702I-B-K9", None, 11, 130, MAIN_NETWORK, SUB_AP, "Cisco", COND_ISLENMIS, *_3702)
add(5, "CISCO AIR CAP3702I-A-K9", None, 26, 130, MAIN_NETWORK, SUB_AP, "Cisco", COND_ISLENMIS, *_3702)

add(6, "CISCO AIR AP3802I-B-K9", None, 8, 250, MAIN_NETWORK, SUB_AP, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz giriş nöqtəsi (daxili, 802.11ac Wave 2)",
     "Standart: IEEE 802.11ac Wave 2",
     "Tezlik: 2.4 GHz + 5 GHz",
     "MIMO: 4×4 (5 GHz) + 4×4 (2.4 GHz)",
     "MU-MIMO: Dəstəklənir",
     "Maks. sürət: 1.7 Gbps (5 GHz) + 800 Mbps (2.4 GHz)",
     "Antena: Daxili (integrated)",
     "Port: 1× 10/100/1000 Ethernet (PoE+)",
     "Güc: IEEE 802.3at PoE+",
     "İdarəetmə: Cisco WLC / Mobility Express"],
    ["Тип: Беспроводная точка доступа (внутренняя, 802.11ac Wave 2)",
     "Стандарт: IEEE 802.11ac Wave 2",
     "Частота: 2.4 ГГц + 5 ГГц",
     "MIMO: 4×4 (5 ГГц) + 4×4 (2.4 ГГц)",
     "MU-MIMO: Поддерживается",
     "Макс. скорость: 1.7 Гбит/с (5 ГГц) + 800 Мбит/с (2.4 ГГц)",
     "Антенна: Встроенная",
     "Порт: 1× 10/100/1000 Ethernet (PoE+)",
     "Питание: IEEE 802.3at PoE+",
     "Управление: Cisco WLC / Mobility Express"],
    ["Type: Wireless access point (indoor, 802.11ac Wave 2)",
     "Standard: IEEE 802.11ac Wave 2",
     "Bands: 2.4 GHz + 5 GHz",
     "MIMO: 4×4 (5 GHz) + 4×4 (2.4 GHz)",
     "MU-MIMO: Supported",
     "Max rate: 1.7 Gbps (5 GHz) + 800 Mbps (2.4 GHz)",
     "Antenna: Built-in",
     "Port: 1× 10/100/1000 Ethernet (PoE+)",
     "Power: IEEE 802.3at PoE+",
     "Management: Cisco WLC / Mobility Express"])

add(8, "ARUBA AP205", None, 2, 80, MAIN_NETWORK, SUB_AP, "Aruba", COND_ISLENMIS,
    ["Tip: Simsiz giriş nöqtəsi (tavan/divar, 802.11ac)",
     "Standart: IEEE 802.11ac/a/b/g/n",
     "Tezlik: 2.4 GHz + 5 GHz",
     "MIMO: 2×2 (5 GHz) + 2×2 (2.4 GHz)",
     "Maks. sürət: 867 Mbps (5 GHz) + 300 Mbps (2.4 GHz)",
     "Antena: Daxili",
     "Port: 1× 10/100/1000 Ethernet (PoE)",
     "Güc: IEEE 802.3af PoE",
     "İdarəetmə: Aruba Controller / Aruba Instant (IAP)"],
    ["Тип: Беспроводная точка доступа (потолочная/настенная, 802.11ac)",
     "Стандарт: IEEE 802.11ac/a/b/g/n",
     "Частота: 2.4 ГГц + 5 ГГц",
     "MIMO: 2×2 (5 ГГц) + 2×2 (2.4 ГГц)",
     "Макс. скорость: 867 Мбит/с (5 ГГц) + 300 Мбит/с (2.4 ГГц)",
     "Антенна: Встроенная",
     "Порт: 1× 10/100/1000 Ethernet (PoE)",
     "Питание: IEEE 802.3af PoE",
     "Управление: Aruba Controller / Aruba Instant (IAP)"],
    ["Type: Wireless access point (ceiling/wall, 802.11ac)",
     "Standard: IEEE 802.11ac/a/b/g/n",
     "Bands: 2.4 GHz + 5 GHz",
     "MIMO: 2×2 (5 GHz) + 2×2 (2.4 GHz)",
     "Max rate: 867 Mbps (5 GHz) + 300 Mbps (2.4 GHz)",
     "Antenna: Built-in",
     "Port: 1× 10/100/1000 Ethernet (PoE)",
     "Power: IEEE 802.3af PoE",
     "Management: Aruba Controller / Aruba Instant (IAP)"])

add(9, "ARUBA AP225", None, 3, 120, MAIN_NETWORK, SUB_AP, "Aruba", COND_ISLENMIS,
    ["Tip: Simsiz giriş nöqtəsi (tavan/divar, 802.11ac)",
     "Standart: IEEE 802.11ac/a/b/g/n",
     "Tezlik: 2.4 GHz + 5 GHz",
     "MIMO: 3×3 (5 GHz) + 3×3 (2.4 GHz)",
     "Maks. sürət: 1300 Mbps (5 GHz) + 450 Mbps (2.4 GHz)",
     "Antena: Daxili",
     "Port: 1× 10/100/1000 Ethernet (PoE+)",
     "Güc: IEEE 802.3at PoE+ / 802.3af PoE",
     "İdarəetmə: Aruba Controller / Aruba Instant (IAP)"],
    ["Тип: Беспроводная точка доступа (потолочная/настенная, 802.11ac)",
     "Стандарт: IEEE 802.11ac/a/b/g/n",
     "Частота: 2.4 ГГц + 5 ГГц",
     "MIMO: 3×3 (5 ГГц) + 3×3 (2.4 ГГц)",
     "Макс. скорость: 1300 Мбит/с (5 ГГц) + 450 Мбит/с (2.4 ГГц)",
     "Антенна: Встроенная",
     "Порт: 1× 10/100/1000 Ethernet (PoE+)",
     "Питание: IEEE 802.3at PoE+ / 802.3af PoE",
     "Управление: Aruba Controller / Aruba Instant (IAP)"],
    ["Type: Wireless access point (ceiling/wall, 802.11ac)",
     "Standard: IEEE 802.11ac/a/b/g/n",
     "Bands: 2.4 GHz + 5 GHz",
     "MIMO: 3×3 (5 GHz) + 3×3 (2.4 GHz)",
     "Max rate: 1300 Mbps (5 GHz) + 450 Mbps (2.4 GHz)",
     "Antenna: Built-in",
     "Port: 1× 10/100/1000 Ethernet (PoE+)",
     "Power: IEEE 802.3at PoE+ / 802.3af PoE",
     "Management: Aruba Controller / Aruba Instant (IAP)"])

# ============ WI-FI KONTROLLER (yeni) ============
SUB_WLC = "Wi-Fi kontroller"

add(82, "CISCO AIR CT2504-K9", None, 1, 320, MAIN_NETWORK, SUB_WLC, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz LAN (WLAN) kontroller",
     "AP dəstəyi: 50-ə qədər Cisco Aironet giriş nöqtəsi",
     "Maks. istifadəçi: 500",
     "Portlar: 2× 10/100/1000 (1× PoE+)",
     "SSID: 512-ə qədər",
     "VLAN: 512",
     "İdarəetmə: Cisco Wireless Control System (WCS)",
     "Güc: 220V AC (daxili enerji təchizatı)"],
    ["Тип: Контроллер беспроводной LAN (WLAN)",
     "Поддержка точек доступа: до 50 Cisco Aironet",
     "Макс. пользователей: 500",
     "Порты: 2× 10/100/1000 (1× PoE+)",
     "SSID: до 512",
     "VLAN: 512",
     "Управление: Cisco Wireless Control System (WCS)",
     "Питание: 220V AC (встроенный блок питания)"],
    ["Type: Wireless LAN (WLAN) controller",
     "AP support: up to 50 Cisco Aironet access points",
     "Max users: 500",
     "Ports: 2× 10/100/1000 (1× PoE+)",
     "SSID: up to 512",
     "VLAN: 512",
     "Management: Cisco Wireless Control System (WCS)",
     "Power: 220V AC (built-in PSU)"])

add(67, "ARUBA 650", None, 1, 470, MAIN_NETWORK, SUB_WLC, "Aruba", COND_ISLENMIS,
    ["Tip: Filial (branch) WLAN kontroller",
     "AP dəstəyi: 64-ə qədər Aruba giriş nöqtəsi",
     "Maks. istifadəçi: 2048",
     "Portlar: 4× 10/100/1000 (2× PoE+)",
     "Roaming: Sürətli L3/L2",
     "Firewall: Daxili stateful firewall",
     "VPN: IPsec (daxili)"],
    ["Тип: Филиальный (branch) WLAN-контроллер",
     "Поддержка точек доступа: до 64 Aruba AP",
     "Макс. пользователей: 2048",
     "Порты: 4× 10/100/1000 (2× PoE+)",
     "Роуминг: Быстрый L3/L2",
     "Firewall: Встроенный stateful firewall",
     "VPN: IPsec (встроенный)"],
    ["Type: Branch WLAN controller",
     "AP support: up to 64 Aruba access points",
     "Max users: 2048",
     "Ports: 4× 10/100/1000 (2× PoE+)",
     "Roaming: Fast L3/L2",
     "Firewall: Built-in stateful firewall",
     "VPN: IPsec (built-in)"])

# ============ KOMMUTATOR ============
SUB_SW = "Kommutator"

_c3850_48 = ([
    "Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 3850)",
    "Portlar: 48× 10/100/1000 Mbps (PoE+)",
    "PoE büdcəsi: 435 W",
    "Uplink: 4× 10G SFP+",
    "StackWise-480: 480 Gbps stack bacarığı",
    "Kommutasiya tutumu: 176 Gbps",
    "Paket ötürmə: 50.7 Mpps",
    "Menecment: IOS XE, Web UI, SNMP, CLI",
    "PoE: IEEE 802.3at PoE+ / 802.3af PoE",
], [
    "Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 3850)",
    "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
    "PoE-бюджет: 435 Вт",
    "Uplink: 4× 10G SFP+",
    "StackWise-480: пропускная способность стека 480 Гбит/с",
    "Коммутационная способность: 176 Гбит/с",
    "Скорость пакетов: 50.7 млн пакетов/с",
    "Управление: IOS XE, Web UI, SNMP, CLI",
    "PoE: IEEE 802.3at PoE+ / 802.3af PoE",
], [
    "Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 3850)",
    "Ports: 48× 10/100/1000 Mbps (PoE+)",
    "PoE budget: 435 W",
    "Uplinks: 4× 10G SFP+",
    "StackWise-480: 480 Gbps stacking bandwidth",
    "Switching capacity: 176 Gbps",
    "Forwarding rate: 50.7 Mpps",
    "Management: IOS XE, Web UI, SNMP, CLI",
    "PoE: IEEE 802.3at PoE+ / 802.3af PoE",
])

add(17, "CISCO WS-C3850-48P-S", None, 16, 750, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3850_48)
add(19, "CISCO WS-C3850-48P-L", None, 2, 750, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3850_48)
add(20, "CISCO WS-C3850-48F-L", None, 3, 750, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3850_48)
add(21, "CISCO WS-C3850-48F-S", None, 2, 750, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3850_48)

add(18, "CISCO WS-C3850-48U-L", None, 2, 850, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 3850)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 435 W (modular universal enerji təchizatı)",
     "Uplink: 4× 10G SFP+",
     "StackWise-480: 480 Gbps stack bacarığı",
     "Kommutasiya tutumu: 176 Gbps",
     "Paket ötürmə: 50.7 Mpps",
     "Menecment: IOS XE, Web UI, SNMP, CLI",
     "PoE: IEEE 802.3at PoE+ / 802.3af PoE"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 3850)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 435 Вт (модульный универсальный БП)",
     "Uplink: 4× 10G SFP+",
     "StackWise-480: пропускная способность стека 480 Гбит/с",
     "Коммутационная способность: 176 Гбит/с",
     "Скорость пакетов: 50.7 млн пакетов/с",
     "Управление: IOS XE, Web UI, SNMP, CLI",
     "PoE: IEEE 802.3at PoE+ / 802.3af PoE"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 3850)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 435 W (modular universal PSU)",
     "Uplinks: 4× 10G SFP+",
     "StackWise-480: 480 Gbps stacking bandwidth",
     "Switching capacity: 176 Gbps",
     "Forwarding rate: 50.7 Mpps",
     "Management: IOS XE, Web UI, SNMP, CLI",
     "PoE: IEEE 802.3at PoE+ / 802.3af PoE"])

_c3850_12s = ([
    "Tip: Stackable Gigabit kommutator (Cisco Catalyst 3850, SFP)",
    "Portlar: 12× 100/1000 SFP (fiber) + 4× 10G SFP+ uplink",
    "StackWise-480: 480 Gbps stack bacarığı",
    "Kommutasiya tutumu: 176 Gbps",
    "Paket ötürmə: 50.7 Mpps",
    "Menecment: IOS XE, Web UI, SNMP, CLI",
    "Korpus: 1U, rack-mount",
], [
    "Тип: Стекируемый гигабитный коммутатор (Cisco Catalyst 3850, SFP)",
    "Порты: 12× 100/1000 SFP (оптика) + 4× 10G SFP+ uplink",
    "StackWise-480: пропускная способность стека 480 Гбит/с",
    "Коммутационная способность: 176 Гбит/с",
    "Скорость пакетов: 50.7 млн пакетов/с",
    "Управление: IOS XE, Web UI, SNMP, CLI",
    "Корпус: 1U, монтаж в стойку",
], [
    "Type: Stackable Gigabit switch (Cisco Catalyst 3850, SFP)",
    "Ports: 12× 100/1000 SFP (fiber) + 4× 10G SFP+ uplinks",
    "StackWise-480: 480 Gbps stacking bandwidth",
    "Switching capacity: 176 Gbps",
    "Forwarding rate: 50.7 Mpps",
    "Management: IOS XE, Web UI, SNMP, CLI",
    "Chassis: 1U, rack-mountable",
])

add(37, "CISCO WS-C3850-12S-S", None, 3, 980, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3850_12s)
add(38, "CISCO WS-C3850-12S-E", None, 1, 990, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3850_12s)

add(22, "CISCO WS-C3560X-48PF-L", None, 1, 600, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 3560-X)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 715 W",
     "Uplink: 4× 10G SFP+",
     "StackPower / FlexStack-Plus",
     "Kommutasiya tutumu: 160 Gbps",
     "Paket ötürmə: 66 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 3560-X)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 715 Вт",
     "Uplink: 4× 10G SFP+",
     "StackPower / FlexStack-Plus",
     "Коммутационная способность: 160 Гбит/с",
     "Скорость пакетов: 66 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 3560-X)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 715 W",
     "Uplinks: 4× 10G SFP+",
     "StackPower / FlexStack-Plus",
     "Switching capacity: 160 Gbps",
     "Forwarding rate: 66 Mpps",
     "Management: IOS, CLI, SNMP"])

add(23, "CISCO WS-C3750X-24T-L", None, 1, 420, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit kommutator (Cisco Catalyst 3750-X)",
     "Portlar: 24× 10/100/1000 Mbps (24T)",
     "Uplink: 2× 10G SFP+",
     "StackWise-Plus: 64 Gbps",
     "Kommutasiya tutumu: 160 Gbps",
     "Paket ötürmə: 65.5 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный коммутатор (Cisco Catalyst 3750-X)",
     "Порты: 24× 10/100/1000 Мбит/с (24T)",
     "Uplink: 2× 10G SFP+",
     "StackWise-Plus: 64 Гбит/с",
     "Коммутационная способность: 160 Гбит/с",
     "Скорость пакетов: 65.5 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit switch (Cisco Catalyst 3750-X)",
     "Ports: 24× 10/100/1000 Mbps (24T)",
     "Uplinks: 2× 10G SFP+",
     "StackWise-Plus: 64 Gbps",
     "Switching capacity: 160 Gbps",
     "Forwarding rate: 65.5 Mpps",
     "Management: IOS, CLI, SNMP"])

_c3750x_48 = ([
    "Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 3750-X)",
    "Portlar: 48× 10/100/1000 Mbps",
    "PoE büdcəsi: 715 W (48PF) / PoE olmadan (48T)",
    "Uplink: 2× 10G SFP+",
    "StackWise-Plus: 64 Gbps",
    "Kommutasiya tutumu: 160 Gbps",
    "Paket ötürmə: 65.5 Mpps",
    "Menecment: IOS, CLI, SNMP",
], [
    "Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 3750-X)",
    "Порты: 48× 10/100/1000 Мбит/с",
    "PoE-бюджет: 715 Вт (48PF) / без PoE (48T)",
    "Uplink: 2× 10G SFP+",
    "StackWise-Plus: 64 Гбит/с",
    "Коммутационная способность: 160 Гбит/с",
    "Скорость пакетов: 65.5 млн пакетов/с",
    "Управление: IOS, CLI, SNMP",
], [
    "Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 3750-X)",
    "Ports: 48× 10/100/1000 Mbps",
    "PoE budget: 715 W (48PF) / no PoE (48T)",
    "Uplinks: 2× 10G SFP+",
    "StackWise-Plus: 64 Gbps",
    "Switching capacity: 160 Gbps",
    "Forwarding rate: 65.5 Mpps",
    "Management: IOS, CLI, SNMP",
])

add(24, "CISCO WS-C3750X-48T-S", None, 1, 440, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3750x_48)
add(25, "CISCO WS-C3750X-48PF-S", None, 1, 510, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3750x_48)

add(26, "CISCO WS4948", None, 2, 500, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Gigabit kommutator (Cisco Catalyst 4948)",
     "Portlar: 48× 10/100/1000 Mbps + 4× 10G SFP+ uplink",
     "Kommutasiya tutumu: 136 Gbps",
     "Paket ötürmə: 102 Mpps",
     "Menecment: IOS, CLI, SNMP",
     "Korpus: 1U, rack-mount",
     "Güc: 2× daxili enerji təchizatı (redundant)"],
    ["Тип: Гигабитный коммутатор (Cisco Catalyst 4948)",
     "Порты: 48× 10/100/1000 Мбит/с + 4× 10G SFP+ uplink",
     "Коммутационная способность: 136 Гбит/с",
     "Скорость пакетов: 102 млн пакетов/с",
     "Управление: IOS, CLI, SNMP",
     "Корпус: 1U, монтаж в стойку",
     "Питание: 2× встроенных БП (резервирование)"],
    ["Type: Gigabit switch (Cisco Catalyst 4948)",
     "Ports: 48× 10/100/1000 Mbps + 4× 10G SFP+ uplinks",
     "Switching capacity: 136 Gbps",
     "Forwarding rate: 102 Mpps",
     "Management: IOS, CLI, SNMP",
     "Chassis: 1U, rack-mountable",
     "Power: 2× built-in PSUs (redundant)"])

_c3650_48 = ([
    "Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 3650)",
    "Portlar: 48× 10/100/1000 Mbps (PoE+)",
    "PoE büdcəsi: 715 W",
    "Uplink: 4× 10G SFP+",
    "Kommutasiya tutumu: 176 Gbps",
    "Paket ötürmə: 50.7 Mpps",
    "Menecment: IOS XE, CLI, SNMP",
    "StackWise-480 dəstəyi",
], [
    "Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 3650)",
    "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
    "PoE-бюджет: 715 Вт",
    "Uplink: 4× 10G SFP+",
    "Коммутационная способность: 176 Гбит/с",
    "Скорость пакетов: 50.7 млн пакетов/с",
    "Управление: IOS XE, CLI, SNMP",
    "Поддержка StackWise-480",
], [
    "Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 3650)",
    "Ports: 48× 10/100/1000 Mbps (PoE+)",
    "PoE budget: 715 W",
    "Uplinks: 4× 10G SFP+",
    "Switching capacity: 176 Gbps",
    "Forwarding rate: 50.7 Mpps",
    "Management: IOS XE, CLI, SNMP",
    "StackWise-480 support",
])

add(27, "CISCO WS-C3650-48PD-S", None, 2, 850, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3650_48)
add(28, "CISCO WS-C3650-48FS-S", None, 17, 720, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3650_48)
add(29, "CISCO WS-C3650-48FS-L", None, 1, 720, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS, *_c3650_48)

add(30, "CISCO WS-C3750E-48PD-EF", None, 1, 510, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 3750-E)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 1150 W (full PoE)",
     "Uplink: 4× X2 10G",
     "StackWise: 32 Gbps stack",
     "Kommutasiya tutumu: 160 Gbps",
     "Paket ötürmə: 65.5 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 3750-E)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 1150 Вт (полный PoE)",
     "Uplink: 4× X2 10G",
     "StackWise: стек 32 Гбит/с",
     "Коммутационная способность: 160 Гбит/с",
     "Скорость пакетов: 65.5 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 3750-E)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 1150 W (full PoE)",
     "Uplinks: 4× X2 10G",
     "StackWise: 32 Gbps stacking",
     "Switching capacity: 160 Gbps",
     "Forwarding rate: 65.5 Mpps",
     "Management: IOS, CLI, SNMP"])

add(31, "CISCO WS-C3560G-24", None, 1, 300, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Gigabit kommutator (Cisco Catalyst 3560-G)",
     "Portlar: 24× 10/100/1000 Mbps + 4× SFP",
     "Kommutasiya tutumu: 32 Gbps",
     "Paket ötürmə: 38.7 Mpps",
     "Menecment: IOS, CLI, SNMP",
     "PoE: Portlar 1–24 (802.3af)"],
    ["Тип: Гигабитный коммутатор (Cisco Catalyst 3560-G)",
     "Порты: 24× 10/100/1000 Мбит/с + 4× SFP",
     "Коммутационная способность: 32 Гбит/с",
     "Скорость пакетов: 38.7 млн пакетов/с",
     "Управление: IOS, CLI, SNMP",
     "PoE: Порты 1–24 (802.3af)"],
    ["Type: Gigabit switch (Cisco Catalyst 3560-G)",
     "Ports: 24× 10/100/1000 Mbps + 4× SFP",
     "Switching capacity: 32 Gbps",
     "Forwarding rate: 38.7 Mpps",
     "Management: IOS, CLI, SNMP",
     "PoE: Ports 1–24 (802.3af)"])

add(32, "CISCO WS-C3750-48P V2", None, 6, 380, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE kommutator (Cisco Catalyst 3750)",
     "Portlar: 48× 10/100/1000 Mbps (PoE)",
     "PoE büdcəsi: 370 W (15.4 W/port)",
     "Uplink: 4× SFP",
     "StackWise: 32 Gbps",
     "Kommutasiya tutumu: 32 Gbps",
     "Paket ötürmə: 38.7 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE коммутатор (Cisco Catalyst 3750)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE)",
     "PoE-бюджет: 370 Вт (15.4 Вт/порт)",
     "Uplink: 4× SFP",
     "StackWise: 32 Гбит/с",
     "Коммутационная способность: 32 Гбит/с",
     "Скорость пакетов: 38.7 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE switch (Cisco Catalyst 3750)",
     "Ports: 48× 10/100/1000 Mbps (PoE)",
     "PoE budget: 370 W (15.4 W/port)",
     "Uplinks: 4× SFP",
     "StackWise: 32 Gbps",
     "Switching capacity: 32 Gbps",
     "Forwarding rate: 38.7 Mpps",
     "Management: IOS, CLI, SNMP"])

add(33, "CISCO WS-C3750-24P V2", None, 2, 330, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE kommutator (Cisco Catalyst 3750)",
     "Portlar: 24× 10/100/1000 Mbps (PoE) + 4× SFP",
     "PoE büdcəsi: 185 W",
     "StackWise: 32 Gbps",
     "Kommutasiya tutumu: 32 Gbps",
     "Paket ötürmə: 38.7 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE коммутатор (Cisco Catalyst 3750)",
     "Порты: 24× 10/100/1000 Мбит/с (PoE) + 4× SFP",
     "PoE-бюджет: 185 Вт",
     "StackWise: 32 Гбит/с",
     "Коммутационная способность: 32 Гбит/с",
     "Скорость пакетов: 38.7 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE switch (Cisco Catalyst 3750)",
     "Ports: 24× 10/100/1000 Mbps (PoE) + 4× SFP",
     "PoE budget: 185 W",
     "StackWise: 32 Gbps",
     "Switching capacity: 32 Gbps",
     "Forwarding rate: 38.7 Mpps",
     "Management: IOS, CLI, SNMP"])

add(34, "CISCO WS-C3560-24P V2", None, 2, 290, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: PoE kommutator (Cisco Catalyst 3560)",
     "Portlar: 24× 10/100 Mbps (PoE) + 2× SFP",
     "PoE büdcəsi: 185 W",
     "Kommutasiya tutumu: 8.8 Gbps",
     "Paket ötürmə: 6.5 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: PoE-коммутатор (Cisco Catalyst 3560)",
     "Порты: 24× 10/100 Мбит/с (PoE) + 2× SFP",
     "PoE-бюджет: 185 Вт",
     "Коммутационная способность: 8.8 Гбит/с",
     "Скорость пакетов: 6.5 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: PoE switch (Cisco Catalyst 3560)",
     "Ports: 24× 10/100 Mbps (PoE) + 2× SFP",
     "PoE budget: 185 W",
     "Switching capacity: 8.8 Gbps",
     "Forwarding rate: 6.5 Mpps",
     "Management: IOS, CLI, SNMP"])

add(35, "CISCO WS-C3750G-12S-S", None, 2, 510, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit SFP kommutator (Cisco Catalyst 3750-G)",
     "Portlar: 12× 100/1000 SFP (fiber) + 4× SFP stack",
     "Kommutasiya tutumu: 32 Gbps",
     "Paket ötürmə: 38.7 Mpps",
     "StackWise: 32 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный SFP коммутатор (Cisco Catalyst 3750-G)",
     "Порты: 12× 100/1000 SFP (оптика) + 4× SFP stack",
     "Коммутационная способность: 32 Гбит/с",
     "Скорость пакетов: 38.7 млн пакетов/с",
     "StackWise: 32 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit SFP switch (Cisco Catalyst 3750-G)",
     "Ports: 12× 100/1000 SFP (fiber) + 4× SFP stacking",
     "Switching capacity: 32 Gbps",
     "Forwarding rate: 38.7 Mpps",
     "StackWise: 32 Gbps",
     "Management: IOS, CLI, SNMP"])

add(36, "CISCO WS-C3750X-12S-S", None, 1, 710, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit SFP kommutator (Cisco Catalyst 3750-X)",
     "Portlar: 12× 100/1000 SFP (fiber) + 2× 10G SFP+ uplink",
     "StackWise-Plus: 64 Gbps",
     "Kommutasiya tutumu: 160 Gbps",
     "Paket ötürmə: 65.5 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный SFP коммутатор (Cisco Catalyst 3750-X)",
     "Порты: 12× 100/1000 SFP (оптика) + 2× 10G SFP+ uplink",
     "StackWise-Plus: 64 Гбит/с",
     "Коммутационная способность: 160 Гбит/с",
     "Скорость пакетов: 65.5 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit SFP switch (Cisco Catalyst 3750-X)",
     "Ports: 12× 100/1000 SFP (fiber) + 2× 10G SFP+ uplinks",
     "StackWise-Plus: 64 Gbps",
     "Switching capacity: 160 Gbps",
     "Forwarding rate: 65.5 Mpps",
     "Management: IOS, CLI, SNMP"])

add(39, "CISCO ME3400", None, 2, 220, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Metro Ethernet kommutator (Cisco ME 3400)",
     "Portlar: 24× 10/100 Mbps + 2× SFP",
     "Ethernet OAM / QinQ / VLAN",
     "Kommutasiya tutumu: 16 Gbps",
     "Paket ötürmə: 6.5 Mpps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Коммутатор Metro Ethernet (Cisco ME 3400)",
     "Порты: 24× 10/100 Мбит/с + 2× SFP",
     "Ethernet OAM / QinQ / VLAN",
     "Коммутационная способность: 16 Гбит/с",
     "Скорость пакетов: 6.5 млн пакетов/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Metro Ethernet switch (Cisco ME 3400)",
     "Ports: 24× 10/100 Mbps + 2× SFP",
     "Ethernet OAM / QinQ / VLAN",
     "Switching capacity: 16 Gbps",
     "Forwarding rate: 6.5 Mpps",
     "Management: IOS, CLI, SNMP"])

add(40, "CISCO WS-CE500G-12TC", None, 2, 200, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Gigabit kommutator (Cisco Catalyst Express 500)",
     "Portlar: 12× 10/100/1000 Mbps (8 port + 4 combo SFP/RJ45)",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: Cisco Network Assistant (Web)",
     "Korpus: Desktop / rack-mount"],
    ["Тип: Гигабитный коммутатор (Cisco Catalyst Express 500)",
     "Порты: 12× 10/100/1000 Мбит/с (8 портов + 4 combo SFP/RJ45)",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: Cisco Network Assistant (Web)",
     "Корпус: Настольный / монтаж в стойку"],
    ["Type: Gigabit switch (Cisco Catalyst Express 500)",
     "Ports: 12× 10/100/1000 Mbps (8 ports + 4 combo SFP/RJ45)",
     "Switching capacity: 24 Gbps",
     "Management: Cisco Network Assistant (Web)",
     "Chassis: Desktop / rack-mountable"])

add(41, "CISCO WS-C2960X-48FPD-L", None, 4, 1100, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 2960-X)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 740 W",
     "Uplink: 4× 10G SFP+",
     "FlexStack-Plus: 80 Gbps",
     "Kommutasiya tutumu: 176 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 2960-X)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 740 Вт",
     "Uplink: 4× 10G SFP+",
     "FlexStack-Plus: 80 Гбит/с",
     "Коммутационная способность: 176 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 2960-X)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 740 W",
     "Uplinks: 4× 10G SFP+",
     "FlexStack-Plus: 80 Gbps",
     "Switching capacity: 176 Gbps",
     "Management: IOS, CLI, SNMP"])

add(42, "CISCO WS-C2960X-48FPS-L", None, 1, 870, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 2960-X)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 370 W",
     "Uplink: 4× 10G SFP+",
     "FlexStack-Plus: 80 Gbps",
     "Kommutasiya tutumu: 176 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 2960-X)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 370 Вт",
     "Uplink: 4× 10G SFP+",
     "FlexStack-Plus: 80 Гбит/с",
     "Коммутационная способность: 176 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 2960-X)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 370 W",
     "Uplinks: 4× 10G SFP+",
     "FlexStack-Plus: 80 Gbps",
     "Switching capacity: 176 Gbps",
     "Management: IOS, CLI, SNMP"])

add(43, "CISCO WS-C2960X-48LPS-L V04", None, 6, 890, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 2960-X)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 370 W",
     "Uplink: 4× 10G SFP+ (2 port aktiv)",
     "FlexStack-Plus: 80 Gbps",
     "Kommutasiya tutumu: 176 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 2960-X)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 370 Вт",
     "Uplink: 4× 10G SFP+ (активны 2 порта)",
     "FlexStack-Plus: 80 Гбит/с",
     "Коммутационная способность: 176 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 2960-X)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 370 W",
     "Uplinks: 4× 10G SFP+ (2 ports active)",
     "FlexStack-Plus: 80 Gbps",
     "Switching capacity: 176 Gbps",
     "Management: IOS, CLI, SNMP"])

add(44, "CISCO WS-C2960S-48LPS-L", None, 6, 550, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 2960-S)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 370 W",
     "Uplink: 2× 10G SFP+",
     "FlexStack: 20 Gbps",
     "Kommutasiya tutumu: 88 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 2960-S)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 370 Вт",
     "Uplink: 2× 10G SFP+",
     "FlexStack: 20 Гбит/с",
     "Коммутационная способность: 88 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 2960-S)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 370 W",
     "Uplinks: 2× 10G SFP+",
     "FlexStack: 20 Gbps",
     "Switching capacity: 88 Gbps",
     "Management: IOS, CLI, SNMP"])

add(45, "CISCO WS-C2960S-F48LPS-L V01", None, 1, 500, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 2960-S, full PoE)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 740 W",
     "Uplink: 2× 10G SFP+",
     "FlexStack: 20 Gbps",
     "Kommutasiya tutumu: 88 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 2960-S, полный PoE)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 740 Вт",
     "Uplink: 2× 10G SFP+",
     "FlexStack: 20 Гбит/с",
     "Коммутационная способность: 88 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 2960-S, full PoE)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 740 W",
     "Uplinks: 2× 10G SFP+",
     "FlexStack: 20 Gbps",
     "Switching capacity: 88 Gbps",
     "Management: IOS, CLI, SNMP"])

add(46, "CISCO WS-C2960S-48LPD-L V04 10G", None, 1, 1000, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Stackable Gigabit PoE+ kommutator (Cisco Catalyst 2960-S, 10G)",
     "Portlar: 48× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 740 W",
     "Uplink: 2× 10G SFP+ (10G versiyası)",
     "FlexStack: 20 Gbps",
     "Kommutasiya tutumu: 88 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Стекируемый гигабитный PoE+ коммутатор (Cisco Catalyst 2960-S, 10G)",
     "Порты: 48× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 740 Вт",
     "Uplink: 2× 10G SFP+ (версия 10G)",
     "FlexStack: 20 Гбит/с",
     "Коммутационная способность: 88 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Stackable Gigabit PoE+ switch (Cisco Catalyst 2960-S, 10G)",
     "Ports: 48× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 740 W",
     "Uplinks: 2× 10G SFP+ (10G version)",
     "FlexStack: 20 Gbps",
     "Switching capacity: 88 Gbps",
     "Management: IOS, CLI, SNMP"])

add(47, "CISCO SRW224G4P-K9", None, 1, 520, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: PoE kommutator (Cisco Small Business SRW224G4P)",
     "Portlar: 24× 10/100 Mbps (PoE) + 4× 10/100/1000 combo",
     "PoE büdcəsi: 104 W",
     "Kommutasiya tutumu: 8.8 Gbps",
     "Menecment: Web / CLI / SNMP"],
    ["Тип: PoE-коммутатор (Cisco Small Business SRW224G4P)",
     "Порты: 24× 10/100 Мбит/с (PoE) + 4× 10/100/1000 combo",
     "PoE-бюджет: 104 Вт",
     "Коммутационная способность: 8.8 Гбит/с",
     "Управление: Web / CLI / SNMP"],
    ["Type: PoE switch (Cisco Small Business SRW224G4P)",
     "Ports: 24× 10/100 Mbps (PoE) + 4× 10/100/1000 combo",
     "PoE budget: 104 W",
     "Switching capacity: 8.8 Gbps",
     "Management: Web / CLI / SNMP"])

add(48, "CISCO WS-C3560C-12PC-S", None, 10, 390, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt Gigabit PoE+ kommutator (Cisco Catalyst 3560-C)",
     "Portlar: 12× 10/100/1000 Mbps (PoE+) + 2× SFP",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: IOS, CLI, SNMP",
     "Güc: Xarici enerji təchizatı / PoE+"],
    ["Тип: Компактный гигабитный PoE+ коммутатор (Cisco Catalyst 3560-C)",
     "Порты: 12× 10/100/1000 Мбит/с (PoE+) + 2× SFP",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: IOS, CLI, SNMP",
     "Питание: Внешний БП / PoE+"],
    ["Type: Compact Gigabit PoE+ switch (Cisco Catalyst 3560-C)",
     "Ports: 12× 10/100/1000 Mbps (PoE+) + 2× SFP",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Switching capacity: 24 Gbps",
     "Management: IOS, CLI, SNMP",
     "Power: External adapter / PoE+"])

add(49, "CISCO WS-C3560CG-8PC-S V03", None, 12, 490, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt Gigabit PoE+ kommutator (Cisco Catalyst 3560-CG)",
     "Portlar: 8× 10/100/1000 Mbps (PoE+) + 2× SFP",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: IOS, CLI, SNMP",
     "Güc: Xarici enerji təchizatı / PoE+"],
    ["Тип: Компактный гигабитный PoE+ коммутатор (Cisco Catalyst 3560-CG)",
     "Порты: 8× 10/100/1000 Мбит/с (PoE+) + 2× SFP",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: IOS, CLI, SNMP",
     "Питание: Внешний БП / PoE+"],
    ["Type: Compact Gigabit PoE+ switch (Cisco Catalyst 3560-CG)",
     "Ports: 8× 10/100/1000 Mbps (PoE+) + 2× SFP",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Switching capacity: 24 Gbps",
     "Management: IOS, CLI, SNMP",
     "Power: External adapter / PoE+"])

add(50, "CISCO WS-C2960C-12PC-L", None, 5, 380, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt Gigabit PoE kommutator (Cisco Catalyst 2960-C)",
     "Portlar: 12× 10/100/1000 Mbps (PoE) + 2× SFP",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Компактный гигабитный PoE коммутатор (Cisco Catalyst 2960-C)",
     "Порты: 12× 10/100/1000 Мбит/с (PoE) + 2× SFP",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Compact Gigabit PoE switch (Cisco Catalyst 2960-C)",
     "Ports: 12× 10/100/1000 Mbps (PoE) + 2× SFP",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Switching capacity: 24 Gbps",
     "Management: IOS, CLI, SNMP"])

add(51, "CISCO WS-C2960C-8PC-L V01", None, 12, 360, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt Gigabit PoE kommutator (Cisco Catalyst 2960-C)",
     "Portlar: 8× 10/100/1000 Mbps (PoE) + 2× SFP",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Компактный гигабитный PoE коммутатор (Cisco Catalyst 2960-C)",
     "Порты: 8× 10/100/1000 Мбит/с (PoE) + 2× SFP",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Compact Gigabit PoE switch (Cisco Catalyst 2960-C)",
     "Ports: 8× 10/100/1000 Mbps (PoE) + 2× SFP",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Switching capacity: 24 Gbps",
     "Management: IOS, CLI, SNMP"])

add(52, "CISCO WS-C2960CPD-8PT-L V01", None, 1, 300, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt Gigabit PoE kommutator (Cisco Catalyst 2960-CPD)",
     "Portlar: 8× 10/100/1000 Mbps (PoE) + 2× SFP uplink",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Компактный гигабитный PoE коммутатор (Cisco Catalyst 2960-CPD)",
     "Порты: 8× 10/100/1000 Мбит/с (PoE) + 2× SFP uplink",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Compact Gigabit PoE switch (Cisco Catalyst 2960-CPD)",
     "Ports: 8× 10/100/1000 Mbps (PoE) + 2× SFP uplinks",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Switching capacity: 24 Gbps",
     "Management: IOS, CLI, SNMP"])

add(53, "CISCO WS-C2960PD-8TT-L", None, 4, 180, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt PoE kommutator (Cisco Catalyst 2960-PD)",
     "Portlar: 8× 10/100 Mbps (PoE)",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Компактный PoE коммутатор (Cisco Catalyst 2960-PD)",
     "Порты: 8× 10/100 Мбит/с (PoE)",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Compact PoE switch (Cisco Catalyst 2960-PD)",
     "Ports: 8× 10/100 Mbps (PoE)",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Management: IOS, CLI, SNMP"])

add(54, "CISCO WS-C3560-12PC-S V03", None, 2, 250, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt Gigabit PoE+ kommutator (Cisco Catalyst 3560-C)",
     "Portlar: 12× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Компактный гигабитный PoE+ коммутатор (Cisco Catalyst 3560-C)",
     "Порты: 12× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Compact Gigabit PoE+ switch (Cisco Catalyst 3560-C)",
     "Ports: 12× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Switching capacity: 24 Gbps",
     "Management: IOS, CLI, SNMP"])

add(55, "CISCO WS-C3560-8PC-S", None, 2, 220, MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
    ["Tip: Kompakt Gigabit PoE+ kommutator (Cisco Catalyst 3560-C)",
     "Portlar: 8× 10/100/1000 Mbps (PoE+)",
     "PoE büdcəsi: 124 W",
     "Fanless: Səssiz işləmə",
     "Kommutasiya tutumu: 24 Gbps",
     "Menecment: IOS, CLI, SNMP"],
    ["Тип: Компактный гигабитный PoE+ коммутатор (Cisco Catalyst 3560-C)",
     "Порты: 8× 10/100/1000 Мбит/с (PoE+)",
     "PoE-бюджет: 124 Вт",
     "Без вентилятора: Бесшумная работа",
     "Коммутационная способность: 24 Гбит/с",
     "Управление: IOS, CLI, SNMP"],
    ["Type: Compact Gigabit PoE+ switch (Cisco Catalyst 3560-C)",
     "Ports: 8× 10/100/1000 Mbps (PoE+)",
     "PoE budget: 124 W",
     "Fanless: Silent operation",
     "Switching capacity: 24 Gbps",
     "Management: IOS, CLI, SNMP"])

_nexus_5k = {
    59: ("N5K-C5020P-BF", 1250,
         "Portlar: 20× 10G SFP+ + 4× 40G QSFP+",
         "Порты: 20× 10G SFP+ + 4× 40G QSFP+",
         "Ports: 20× 10G SFP+ + 4× 40G QSFP+"),
    60: ("N5K-C5548UP", 1300,
         "Portlar: 32× 10G SFP+ (unified) + 4× 40G QSFP+",
         "Порты: 32× 10G SFP+ (унифицированные) + 4× 40G QSFP+",
         "Ports: 32× 10G SFP+ (unified) + 4× 40G QSFP+"),
    61: ("N5K-5010-P-BF", 1200,
         "Portlar: 20× 10G SFP+",
         "Порты: 20× 10G SFP+",
         "Ports: 20× 10G SFP+"),
}

for _n, (_model, _price, _p_az, _p_ru, _p_en) in _nexus_5k.items():
    add(_n, f"CISCO {_model}", None, 0 if _n == 61 else (2 if _n == 59 else 1), _price,
        MAIN_NETWORK, SUB_SW, "Cisco", COND_ISLENMIS,
        ["Tip: Data center kommutatoru (Cisco Nexus 5000)",
         _p_az,
         "Kommutasiya tutumu: 520 Gbps",
         "Latency: Aşağı (üniform 10G)",
         "FCoE: Dəstəklənir (unified port)",
         "Menecment: NX-OS, CLI, SNMP",
         "Korpus: 1U, rack-mount"],
        ["Тип: Датацентровый коммутатор (Cisco Nexus 5000)",
         _p_ru,
         "Коммутационная способность: 520 Гбит/с",
         "Задержка: Низкая (ровный 10G)",
         "FCoE: Поддерживается (унифицированные порты)",
         "Управление: NX-OS, CLI, SNMP",
         "Корпус: 1U, монтаж в стойку"],
        ["Type: Data center switch (Cisco Nexus 5000)",
         _p_en,
         "Switching capacity: 520 Gbps",
         "Latency: Low (uniform 10G)",
         "FCoE: Supported (unified ports)",
         "Management: NX-OS, CLI, SNMP",
         "Chassis: 1U, rack-mountable"])

add(68, "ARUBA S1500-12P", None, 1, 250, MAIN_NETWORK, SUB_SW, "Aruba", COND_ISLENMIS,
    ["Tip: Gigabit PoE+ kommutator (Aruba S1500-12P)",
     "Portlar: 12× 10/100/1000 Mbps (8× PoE+) + 2× SFP combo",
     "PoE büdcəsi: 46 W",
     "Menecment: Web / CLI / SNMP",
     "Korpus: Desktop / rack-mount"],
    ["Тип: Гигабитный PoE+ коммутатор (Aruba S1500-12P)",
     "Порты: 12× 10/100/1000 Мбит/с (8× PoE+) + 2× SFP combo",
     "PoE-бюджет: 46 Вт",
     "Управление: Web / CLI / SNMP",
     "Корпус: Настольный / монтаж в стойку"],
    ["Type: Gigabit PoE+ switch (Aruba S1500-12P)",
     "Ports: 12× 10/100/1000 Mbps (8× PoE+) + 2× SFP combo",
     "PoE budget: 46 W",
     "Management: Web / CLI / SNMP",
     "Chassis: Desktop / rack-mountable"])

add(69, "HP 2520-8 POE J9137A", None, 5, 200, MAIN_NETWORK, SUB_SW, "HP", COND_ISLENMIS,
    ["Tip: PoE kommutator (HP ProCurve 2520-8 PoE)",
     "Portlar: 8× 10/100 Mbps (PoE) + 2× dual-personality 10/100/1000",
     "PoE büdcəsi: 68 W",
     "Menecment: CLI / Web / SNMP (managed)",
     "Korpus: Desktop / rack-mount"],
    ["Тип: PoE-коммутатор (HP ProCurve 2520-8 PoE)",
     "Порты: 8× 10/100 Мбит/с (PoE) + 2× dual-personality 10/100/1000",
     "PoE-бюджет: 68 Вт",
     "Управление: CLI / Web / SNMP (управляемый)",
     "Корпус: Настольный / монтаж в стойку"],
    ["Type: PoE switch (HP ProCurve 2520-8 PoE)",
     "Ports: 8× 10/100 Mbps (PoE) + 2× dual-personality 10/100/1000",
     "PoE budget: 68 W",
     "Management: CLI / Web / SNMP (managed)",
     "Chassis: Desktop / rack-mountable"])

# ---- TPLink switches (Yeni) ----
add(84, "TPLINK TL-SL1218P", None, 1, 301.99, MAIN_NETWORK, SUB_SW, "TP-Link", COND_YENI,
    ["Tip: Idarəolunmaz PoE+ kommutator (TP-Link TL-SL1218P)",
     "Portlar: 16× 10/100 Mbps PoE+ + 2× 10/100/1000 RJ45 + 1× combo Gigabit SFP",
     "PoE büdcəsi: 150 W (port başına 30 W-a qədər)",
     "PoE standartı: IEEE 802.3af/at",
     "Extend Mode: 250 m-ə qədər (video nəzarət üçün)",
     "Isolation / Priority rejimləri",
     "Kommutasiya tutumu: 7.2 Gbps",
     "Korpus: Metal, rack-mount"],
    ["Тип: Неуправляемый PoE+ коммутатор (TP-Link TL-SL1218P)",
     "Порты: 16× 10/100 Мбит/с PoE+ + 2× 10/100/1000 RJ45 + 1× combo Gigabit SFP",
     "PoE-бюджет: 150 Вт (до 30 Вт на порт)",
     "Стандарт PoE: IEEE 802.3af/at",
     "Extend Mode: до 250 м (для видеонаблюдения)",
     "Режимы Isolation / Priority",
     "Коммутационная способность: 7.2 Гбит/с",
     "Корпус: Металлический, монтаж в стойку"],
    ["Type: Unmanaged PoE+ switch (TP-Link TL-SL1218P)",
     "Ports: 16× 10/100 Mbps PoE+ + 2× 10/100/1000 RJ45 + 1× combo Gigabit SFP",
     "PoE budget: 150 W (up to 30 W per port)",
     "PoE standard: IEEE 802.3af/at",
     "Extend Mode: up to 250 m (for surveillance)",
     "Isolation / Priority modes",
     "Switching capacity: 7.2 Gbps",
     "Chassis: Metal, rack-mountable"])

add(85, "TPLINK SG2218P", None, 1, 457.99, MAIN_NETWORK, SUB_SW, "TP-Link", COND_YENI,
    ["Tip: Gigabit PoE+ smart kommutator (TP-Link JetStream SG2218P)",
     "Portlar: 16× 10/100/1000 Mbps PoE+ + 2× Gigabit SFP",
     "PoE büdcəsi: 150 W (port başına 30 W-a qədər)",
     "PoE standartı: IEEE 802.3af/at",
     "Menecment: Omada SDN (cloud) / Web / CLI / SNMP",
     "VLAN, ACL, QoS, IGMP Snooping",
     "Static Routing (L2+)",
     "Korpus: Metal, rack-mount"],
    ["Тип: Гигабитный PoE+ smart коммутатор (TP-Link JetStream SG2218P)",
     "Порты: 16× 10/100/1000 Мбит/с PoE+ + 2× Gigabit SFP",
     "PoE-бюджет: 150 Вт (до 30 Вт на порт)",
     "Стандарт PoE: IEEE 802.3af/at",
     "Управление: Omada SDN (облако) / Web / CLI / SNMP",
     "VLAN, ACL, QoS, IGMP Snooping",
     "Static Routing (L2+)",
     "Корпус: Металлический, монтаж в стойку"],
    ["Type: Gigabit PoE+ smart switch (TP-Link JetStream SG2218P)",
     "Ports: 16× 10/100/1000 Mbps PoE+ + 2× Gigabit SFP",
     "PoE budget: 150 W (up to 30 W per port)",
     "PoE standard: IEEE 802.3af/at",
     "Management: Omada SDN (cloud) / Web / CLI / SNMP",
     "VLAN, ACL, QoS, IGMP Snooping",
     "Static Routing (L2+)",
     "Chassis: Metal, rack-mountable"])

add(86, "TPLINK TL-SL1226P", None, 1, 381.99, MAIN_NETWORK, SUB_SW, "TP-Link", COND_YENI,
    ["Tip: Idarəolunmaz PoE+ kommutator (TP-Link TL-SL1226P)",
     "Portlar: 24× 10/100 Mbps PoE+ + 2× 10/100/1000 RJ45 + 2× combo Gigabit SFP",
     "PoE büdcəsi: 250 W (port başına 30 W-a qədər)",
     "PoE standartı: IEEE 802.3af/at",
     "Extend Mode: 250 m-ə qədər (video nəzarət üçün)",
     "Isolation / Priority rejimləri",
     "Kommutasiya tutumu: 8.8 Gbps",
     "Korpus: Metal, rack-mount"],
    ["Тип: Неуправляемый PoE+ коммутатор (TP-Link TL-SL1226P)",
     "Порты: 24× 10/100 Мбит/с PoE+ + 2× 10/100/1000 RJ45 + 2× combo Gigabit SFP",
     "PoE-бюджет: 250 Вт (до 30 Вт на порт)",
     "Стандарт PoE: IEEE 802.3af/at",
     "Extend Mode: до 250 м (для видеонаблюдения)",
     "Режимы Isolation / Priority",
     "Коммутационная способность: 8.8 Гбит/с",
     "Корпус: Металлический, монтаж в стойку"],
    ["Type: Unmanaged PoE+ switch (TP-Link TL-SL1226P)",
     "Ports: 24× 10/100 Mbps PoE+ + 2× 10/100/1000 RJ45 + 2× combo Gigabit SFP",
     "PoE budget: 250 W (up to 30 W per port)",
     "PoE standard: IEEE 802.3af/at",
     "Extend Mode: up to 250 m (for surveillance)",
     "Isolation / Priority modes",
     "Switching capacity: 8.8 Gbps",
     "Chassis: Metal, rack-mountable"])

add(87, "TPLINK SG2210MP", None, 1, 336.99, MAIN_NETWORK, SUB_SW, "TP-Link", COND_YENI,
    ["Tip: Gigabit PoE+ smart kommutator (TP-Link Omada SG2210MP)",
     "Portlar: 8× 10/100/1000 Mbps PoE+ + 2× Gigabit SFP",
     "PoE büdcəsi: 150 W (port başına 30 W-a qədər)",
     "PoE standartı: IEEE 802.3af/at",
     "Menecment: Omada SDN (cloud) / Web / CLI / SNMP",
     "VLAN, ACL, QoS, IGMP Snooping",
     "Korpus: Metal, desktop/rack-mount"],
    ["Тип: Гигабитный PoE+ smart коммутатор (TP-Link Omada SG2210MP)",
     "Порты: 8× 10/100/1000 Мбит/с PoE+ + 2× Gigabit SFP",
     "PoE-бюджет: 150 Вт (до 30 Вт на порт)",
     "Стандарт PoE: IEEE 802.3af/at",
     "Управление: Omada SDN (облако) / Web / CLI / SNMP",
     "VLAN, ACL, QoS, IGMP Snooping",
     "Корпус: Металлический, настольный/стойка"],
    ["Type: Gigabit PoE+ smart switch (TP-Link Omada SG2210MP)",
     "Ports: 8× 10/100/1000 Mbps PoE+ + 2× Gigabit SFP",
     "PoE budget: 150 W (up to 30 W per port)",
     "PoE standard: IEEE 802.3af/at",
     "Management: Omada SDN (cloud) / Web / CLI / SNMP",
     "VLAN, ACL, QoS, IGMP Snooping",
     "Chassis: Metal, desktop/rack-mountable"])

add(88, "TPLINK SG3452P", None, 1, 1323.99, MAIN_NETWORK, SUB_SW, "TP-Link", COND_YENI,
    ["Tip: Gigabit PoE+ L2+ managed kommutator (TP-Link Omada SG3452P)",
     "Portlar: 48× 10/100/1000 Mbps PoE+ + 4× Gigabit SFP",
     "PoE büdcəsi: 384 W (port başına 30 W-a qədər)",
     "PoE standartı: IEEE 802.3af/at",
     "Menecment: Omada SDN (cloud) / Web / CLI / SNMP / RMON",
     "Static Routing, VLAN, ACL, QoS, IGMP Snooping, OAM",
     "Kommutasiya tutumu: 104 Gbps",
     "Paket ötürmə: 77.4 Mpps",
     "Korpus: Metal, rack-mount"],
    ["Тип: Гигабитный PoE+ L2+ управляемый коммутатор (TP-Link Omada SG3452P)",
     "Порты: 48× 10/100/1000 Мбит/с PoE+ + 4× Gigabit SFP",
     "PoE-бюджет: 384 Вт (до 30 Вт на порт)",
     "Стандарт PoE: IEEE 802.3af/at",
     "Управление: Omada SDN (облако) / Web / CLI / SNMP / RMON",
     "Static Routing, VLAN, ACL, QoS, IGMP Snooping, OAM",
     "Коммутационная способность: 104 Гбит/с",
     "Скорость пакетов: 77.4 млн пакетов/с",
     "Корпус: Металлический, монтаж в стойку"],
    ["Type: Gigabit PoE+ L2+ managed switch (TP-Link Omada SG3452P)",
     "Ports: 48× 10/100/1000 Mbps PoE+ + 4× Gigabit SFP",
     "PoE budget: 384 W (up to 30 W per port)",
     "PoE standard: IEEE 802.3af/at",
     "Management: Omada SDN (cloud) / Web / CLI / SNMP / RMON",
     "Static Routing, VLAN, ACL, QoS, IGMP Snooping, OAM",
     "Switching capacity: 104 Gbps",
     "Forwarding rate: 77.4 Mpps",
     "Chassis: Metal, rack-mountable"])

add(89, "TPLINK SG3428MP", None, 1, 824.99, MAIN_NETWORK, SUB_SW, "TP-Link", COND_YENI,
    ["Tip: Gigabit PoE+ L2+ managed kommutator (TP-Link Omada SG3428MP)",
     "Portlar: 24× 10/100/1000 Mbps PoE+ + 4× Gigabit SFP",
     "PoE büdcəsi: 384 W (port başına 30 W-a qədər)",
     "PoE standartı: IEEE 802.3af/at",
     "Menecment: Omada SDN (cloud) / Web / CLI / SNMP / RMON",
     "Static Routing, VLAN, ACL, QoS, IGMP Snooping, OAM",
     "Korpus: Metal, rack-mount"],
    ["Тип: Гигабитный PoE+ L2+ управляемый коммутатор (TP-Link Omada SG3428MP)",
     "Порты: 24× 10/100/1000 Мбит/с PoE+ + 4× Gigabit SFP",
     "PoE-бюджет: 384 Вт (до 30 Вт на порт)",
     "Стандарт PoE: IEEE 802.3af/at",
     "Управление: Omada SDN (облако) / Web / CLI / SNMP / RMON",
     "Static Routing, VLAN, ACL, QoS, IGMP Snooping, OAM",
     "Корпус: Металлический, монтаж в стойку"],
    ["Type: Gigabit PoE+ L2+ managed switch (TP-Link Omada SG3428MP)",
     "Ports: 24× 10/100/1000 Mbps PoE+ + 4× Gigabit SFP",
     "PoE budget: 384 W (up to 30 W per port)",
     "PoE standard: IEEE 802.3af/at",
     "Management: Omada SDN (cloud) / Web / CLI / SNMP / RMON",
     "Static Routing, VLAN, ACL, QoS, IGMP Snooping, OAM",
     "Chassis: Metal, rack-mountable"])

# ============ ROUTER ============
SUB_ROUTER = "Router"

add(62, "CISCO 3925 ROUTER", None, 3, 650, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Integrated Services Router (Cisco ISR 3925, G2)",
     "Portlar: 3× 10/100/1000 GE (2× SFP)",
     "Slots: 4× EHWIC + 2× SM (service module)",
     "Maks. sürət: 1 Gbps (upstream)",
     "VPN: 800 Mbps (IPsec)",
     "Təhlükəsizlik: Zone-based firewall, IPS",
     "Səs: DSP dəstəyi (PVDM3)",
     "Korpus: 2U, rack-mount"],
    ["Тип: Маршрутизатор Integrated Services (Cisco ISR 3925, G2)",
     "Порты: 3× 10/100/1000 GE (2× SFP)",
     "Слоты: 4× EHWIC + 2× SM",
     "Макс. скорость: 1 Гбит/с (upstream)",
     "VPN: 800 Мбит/с (IPsec)",
     "Безопасность: Zone-based firewall, IPS",
     "Голос: Поддержка DSP (PVDM3)",
     "Корпус: 2U, монтаж в стойку"],
    ["Type: Integrated Services Router (Cisco ISR 3925, G2)",
     "Ports: 3× 10/100/1000 GE (2× SFP)",
     "Slots: 4× EHWIC + 2× SM",
     "Max throughput: 1 Gbps (upstream)",
     "VPN: 800 Mbps (IPsec)",
     "Security: Zone-based firewall, IPS",
     "Voice: DSP support (PVDM3)",
     "Chassis: 2U, rack-mountable"])

add(63, "CISCO ISR4431/K9", None, 1, 700, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Integrated Services Router (Cisco ISR 4431)",
     "Portlar: 4× 10/100/1000 GE (SFP)",
     "Slots: 2× NIM + 1× SM",
     "Maks. sürət: 2 Gbps (şifrəsiz)",
     "VPN: 1.6 Gbps (IPsec)",
     "AppNav / WAAS dəstəyi",
     "Təhlükəsizlik: Zone-based firewall, IPS",
     "Korpus: 2U, rack-mount"],
    ["Тип: Маршрутизатор Integrated Services (Cisco ISR 4431)",
     "Порты: 4× 10/100/1000 GE (SFP)",
     "Слоты: 2× NIM + 1× SM",
     "Макс. скорость: 2 Гбит/с (без шифрования)",
     "VPN: 1.6 Гбит/с (IPsec)",
     "Поддержка AppNav / WAAS",
     "Безопасность: Zone-based firewall, IPS",
     "Корпус: 2U, монтаж в стойку"],
    ["Type: Integrated Services Router (Cisco ISR 4431)",
     "Ports: 4× 10/100/1000 GE (SFP)",
     "Slots: 2× NIM + 1× SM",
     "Max throughput: 2 Gbps (unencrypted)",
     "VPN: 1.6 Gbps (IPsec)",
     "AppNav / WAAS support",
     "Security: Zone-based firewall, IPS",
     "Chassis: 2U, rack-mountable"])

add(64, "CISCO CT-7300-1", None, 1, 480, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Edge router (Cisco 7300 seriyası)",
     "Prosessor: NSE-100 (PXF sürətləndirmə)",
     "Portlar: 2× Gigabit Ethernet (daxili)",
     "Genişləndirmə: 4 slot (OC-3 – OC-48)",
     "MPLS: Dəstəklənir",
     "Korpus: 4RU, rack-mount",
     "Güc: 100–240V AC"],
    ["Тип: Пограничный маршрутизатор (серия Cisco 7300)",
     "Процессор: NSE-100 (аппаратное ускорение PXF)",
     "Порты: 2× Gigabit Ethernet (встроенные)",
     "Расширение: 4 слота (OC-3 – OC-48)",
     "MPLS: Поддерживается",
     "Корпус: 4RU, монтаж в стойку",
     "Питание: 100–240V AC"],
    ["Type: Edge router (Cisco 7300 series)",
     "Processor: NSE-100 (PXF acceleration)",
     "Ports: 2× Gigabit Ethernet (built-in)",
     "Expansion: 4 slots (OC-3 – OC-48)",
     "MPLS: Supported",
     "Chassis: 4RU, rack-mountable",
     "Power: 100–240V AC"])

add(70, "CISCO 2921/K9", None, 1, 470, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Integrated Services Router (Cisco ISR 2921, G2)",
     "Portlar: 2× 10/100/1000 GE + 2× EHWIC slot",
     "Maks. sürət: 75 Mbps",
     "VPN: 80 Mbps (IPsec)",
     "Təhlükəsizlik: Zone-based firewall",
     "Səs: DSP dəstəyi",
     "Korpus: 1U, rack-mount"],
    ["Тип: Маршрутизатор Integrated Services (Cisco ISR 2921, G2)",
     "Порты: 2× 10/100/1000 GE + 2 слота EHWIC",
     "Макс. скорость: 75 Мбит/с",
     "VPN: 80 Мбит/с (IPsec)",
     "Безопасность: Zone-based firewall",
     "Голос: Поддержка DSP",
     "Корпус: 1U, монтаж в стойку"],
    ["Type: Integrated Services Router (Cisco ISR 2921, G2)",
     "Ports: 2× 10/100/1000 GE + 2 EHWIC slots",
     "Max throughput: 75 Mbps",
     "VPN: 80 Mbps (IPsec)",
     "Security: Zone-based firewall",
     "Voice: DSP support",
     "Chassis: 1U, rack-mountable"])

add(71, "CISCO SPIAD2901-8FXS/K9", None, 3, 290, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Səs routeri (Cisco 2901 ISR, 8× FXS)",
     "Portlar: 2× 10/100/1000 GE",
     "Analoq səs: 8× FXS port (analoq telefonlar üçün)",
     "Slots: 2× EHWIC + 1× PVDM",
     "Səs kodakları: G.711, G.729, G.722",
     "SIP / H.323: Dəstəklənir",
     "Korpus: 1U, rack-mount"],
    ["Тип: Голосовой маршрутизатор (Cisco 2901 ISR, 8× FXS)",
     "Порты: 2× 10/100/1000 GE",
     "Аналоговый голос: 8× портов FXS (для аналоговых телефонов)",
     "Слоты: 2× EHWIC + 1× PVDM",
     "Голосовые кодеки: G.711, G.729, G.722",
     "SIP / H.323: Поддерживается",
     "Корпус: 1U, монтаж в стойку"],
    ["Type: Voice router (Cisco 2901 ISR, 8× FXS)",
     "Ports: 2× 10/100/1000 GE",
     "Analog voice: 8× FXS ports (for analog phones)",
     "Slots: 2× EHWIC + 1× PVDM",
     "Voice codecs: G.711, G.729, G.722",
     "SIP / H.323: Supported",
     "Chassis: 1U, rack-mountable"])

add(72, "CISCO 2821", None, 2, 190, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Integrated Services Router (Cisco ISR 2821)",
     "Portlar: 2× 10/100/1000 GE",
     "Slots: 2× HWIC + 2× PVDM",
     "Maks. sürət: 90 Mbps",
     "VPN: 45 Mbps (IPsec)",
     "Səs: DSP dəstəyi",
     "Korpus: 2U, rack-mount"],
    ["Тип: Маршрутизатор Integrated Services (Cisco ISR 2821)",
     "Порты: 2× 10/100/1000 GE",
     "Слоты: 2× HWIC + 2× PVDM",
     "Макс. скорость: 90 Мбит/с",
     "VPN: 45 Мбит/с (IPsec)",
     "Голос: Поддержка DSP",
     "Корпус: 2U, монтаж в стойку"],
    ["Type: Integrated Services Router (Cisco ISR 2821)",
     "Ports: 2× 10/100/1000 GE",
     "Slots: 2× HWIC + 2× PVDM",
     "Max throughput: 90 Mbps",
     "VPN: 45 Mbps (IPsec)",
     "Voice: DSP support",
     "Chassis: 2U, rack-mountable"])

add(73, "CISCO 2621XM Router", None, 1, 160, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Modul access router (Cisco 2621XM)",
     "Portlar: 2× 10/100 Ethernet",
     "Slots: 2× WIC + 1× NM",
     "Maks. sürət: 70 Kpps",
     "Menecment: IOS, CLI",
     "Korpus: Desktop / rack-mount"],
    ["Тип: Модульный маршрутизатор доступа (Cisco 2621XM)",
     "Порты: 2× 10/100 Ethernet",
     "Слоты: 2× WIC + 1× NM",
     "Макс. скорость: 70 тыс. пакетов/с",
     "Управление: IOS, CLI",
     "Корпус: Настольный / монтаж в стойку"],
    ["Type: Modular access router (Cisco 2621XM)",
     "Ports: 2× 10/100 Ethernet",
     "Slots: 2× WIC + 1× NM",
     "Max rate: 70 Kpps",
     "Management: IOS, CLI",
     "Chassis: Desktop / rack-mountable"])

add(74, "CISCO 1941/K9", None, 2, 280, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Integrated Services Router (Cisco ISR 1941, G2)",
     "Portlar: 2× 10/100/1000 GE",
     "Slots: 1× EHWIC + 1× ISM",
     "Maks. sürət: 25 Mbps",
     "VPN: 15 Mbps (IPsec)",
     "Təhlükəsizlik: Zone-based firewall",
     "Korpus: Desktop / rack-mount"],
    ["Тип: Маршрутизатор Integrated Services (Cisco ISR 1941, G2)",
     "Порты: 2× 10/100/1000 GE",
     "Слоты: 1× EHWIC + 1× ISM",
     "Макс. скорость: 25 Мбит/с",
     "VPN: 15 Мбит/с (IPsec)",
     "Безопасность: Zone-based firewall",
     "Корпус: Настольный / монтаж в стойку"],
    ["Type: Integrated Services Router (Cisco ISR 1941, G2)",
     "Ports: 2× 10/100/1000 GE",
     "Slots: 1× EHWIC + 1× ISM",
     "Max throughput: 25 Mbps",
     "VPN: 15 Mbps (IPsec)",
     "Security: Zone-based firewall",
     "Chassis: Desktop / rack-mountable"])

add(75, "CISCO 1921/K9", None, 4, 300, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Integrated Services Router (Cisco ISR 1921, G2)",
     "Portlar: 2× 10/100/1000 GE",
     "Slots: 1× EHWIC + 1× ISM",
     "Maks. sürət: 15 Mbps",
     "VPN: 8 Mbps (IPsec)",
     "Təhlükəsizlik: Zone-based firewall",
     "Korpus: Desktop / rack-mount"],
    ["Тип: Маршрутизатор Integrated Services (Cisco ISR 1921, G2)",
     "Порты: 2× 10/100/1000 GE",
     "Слоты: 1× EHWIC + 1× ISM",
     "Макс. скорость: 15 Мбит/с",
     "VPN: 8 Мбит/с (IPsec)",
     "Безопасность: Zone-based firewall",
     "Корпус: Настольный / монтаж в стойку"],
    ["Type: Integrated Services Router (Cisco ISR 1921, G2)",
     "Ports: 2× 10/100/1000 GE",
     "Slots: 1× EHWIC + 1× ISM",
     "Max throughput: 15 Mbps",
     "VPN: 8 Mbps (IPsec)",
     "Security: Zone-based firewall",
     "Chassis: Desktop / rack-mountable"])

add(76, "CISCO C819G 4G A-K9", None, 2, 280, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: 4G LTE router (Cisco 819G)",
     "Əlaqə: 4G LTE (SIM kart) / 3G / 2G",
     "Portlar: 4× 10/100 LAN + 1× 10/100 WAN",
     "Wi-Fi: 802.11n (2.4 GHz)",
     "VPN: IPsec, DMVPN",
     "Təhlükəsizlik: Zone-based firewall",
     "Korpus: Kompakt, DIN-rail/desktop"],
    ["Тип: 4G LTE маршрутизатор (Cisco 819G)",
     "Связь: 4G LTE (SIM-карта) / 3G / 2G",
     "Порты: 4× 10/100 LAN + 1× 10/100 WAN",
     "Wi-Fi: 802.11n (2.4 ГГц)",
     "VPN: IPsec, DMVPN",
     "Безопасность: Zone-based firewall",
     "Корпус: Компактный, DIN-рейка/настольный"],
    ["Type: 4G LTE router (Cisco 819G)",
     "Connectivity: 4G LTE (SIM card) / 3G / 2G",
     "Ports: 4× 10/100 LAN + 1× 10/100 WAN",
     "Wi-Fi: 802.11n (2.4 GHz)",
     "VPN: IPsec, DMVPN",
     "Security: Zone-based firewall",
     "Chassis: Compact, DIN-rail/desktop"])

add(77, "CISCO 881GW GN-A-K9", None, 2, 280, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz + 3G router (Cisco 881G)",
     "Əlaqə: 3G HSPA (SIM kart) + Wi-Fi 802.11n",
     "Portlar: 4× 10/100 LAN + 1× 10/100 WAN",
     "VPN: IPsec, DMVPN",
     "Təhlükəsizlik: Zone-based firewall",
     "Korpus: Desktop"],
    ["Тип: Беспроводной + 3G маршрутизатор (Cisco 881G)",
     "Связь: 3G HSPA (SIM-карта) + Wi-Fi 802.11n",
     "Порты: 4× 10/100 LAN + 1× 10/100 WAN",
     "VPN: IPsec, DMVPN",
     "Безопасность: Zone-based firewall",
     "Корпус: Настольный"],
    ["Type: Wireless + 3G router (Cisco 881G)",
     "Connectivity: 3G HSPA (SIM card) + Wi-Fi 802.11n",
     "Ports: 4× 10/100 LAN + 1× 10/100 WAN",
     "VPN: IPsec, DMVPN",
     "Security: Zone-based firewall",
     "Chassis: Desktop"])

add(78, "CISCO 881W GN-A-K9", None, 1, 250, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz router (Cisco 881W)",
     "Wi-Fi: 802.11n (2.4 GHz)",
     "Portlar: 4× 10/100 LAN + 1× 10/100 WAN",
     "VPN: IPsec, DMVPN",
     "Təhlükəsizlik: Zone-based firewall",
     "Korpus: Desktop"],
    ["Тип: Беспроводной маршрутизатор (Cisco 881W)",
     "Wi-Fi: 802.11n (2.4 ГГц)",
     "Порты: 4× 10/100 LAN + 1× 10/100 WAN",
     "VPN: IPsec, DMVPN",
     "Безопасность: Zone-based firewall",
     "Корпус: Настольный"],
    ["Type: Wireless router (Cisco 881W)",
     "Wi-Fi: 802.11n (2.4 GHz)",
     "Ports: 4× 10/100 LAN + 1× 10/100 WAN",
     "VPN: IPsec, DMVPN",
     "Security: Zone-based firewall",
     "Chassis: Desktop"])

add(79, "CISCO 891FW-A-K9", None, 2, 230, MAIN_NETWORK, SUB_ROUTER, "Cisco", COND_ISLENMIS,
    ["Tip: Firewall router (Cisco 891F)",
     "Portlar: 8× 10/100 LAN + 1× 10/100 WAN",
     "Wi-Fi: 802.11n (2.4 GHz)",
     "Təhlükəsizlik: Zone-based firewall, IPS",
     "VPN: IPsec, DMVPN, EasyVPN",
     "Korpus: Desktop"],
    ["Тип: Маршрутизатор с firewall (Cisco 891F)",
     "Порты: 8× 10/100 LAN + 1× 10/100 WAN",
     "Wi-Fi: 802.11n (2.4 ГГц)",
     "Безопасность: Zone-based firewall, IPS",
     "VPN: IPsec, DMVPN, EasyVPN",
     "Корпус: Настольный"],
    ["Type: Firewall router (Cisco 891F)",
     "Ports: 8× 10/100 LAN + 1× 10/100 WAN",
     "Wi-Fi: 802.11n (2.4 GHz)",
     "Security: Zone-based firewall, IPS",
     "VPN: IPsec, DMVPN, EasyVPN",
     "Chassis: Desktop"])

# ============ FIREWALL (yeni) ============
SUB_FW = "Firewall"

add(65, "FORTINET FWF-80CM", None, 2, 140, MAIN_NETWORK, SUB_FW, "Fortinet", COND_ISLENMIS,
    ["Tip: Simsiz təhlükəsizlik cihazı (FortiWiFi 80CM)",
     "Portlar: 5× 10/100/1000 GE (DMZ/WAN)",
     "Wi-Fi: 802.11n (2.4 GHz, daxili antena)",
     "Firewall sürəti: 900 Mbps",
     "VPN sürəti: 50 Mbps (IPsec)",
     "IPS / Antivirus / Web filter: Daxili",
     "Veb idarəetmə: FortiOS"],
    ["Тип: Беспроводное устройство безопасности (FortiWiFi 80CM)",
     "Порты: 5× 10/100/1000 GE (DMZ/WAN)",
     "Wi-Fi: 802.11n (2.4 ГГц, встроенная антенна)",
     "Скорость firewall: 900 Мбит/с",
     "Скорость VPN: 50 Мбит/с (IPsec)",
     "IPS / Антивирус / Веб-фильтр: Встроенные",
     "Управление: FortiOS"],
    ["Type: Wireless security appliance (FortiWiFi 80CM)",
     "Ports: 5× 10/100/1000 GE (DMZ/WAN)",
     "Wi-Fi: 802.11n (2.4 GHz, built-in antenna)",
     "Firewall throughput: 900 Mbps",
     "VPN throughput: 50 Mbps (IPsec)",
     "IPS / Antivirus / Web filter: Built-in",
     "Management: FortiOS"])

add(66, "PALOALTO PA-500", None, 1, 250, MAIN_NETWORK, SUB_FW, "Palo Alto", COND_ISLENMIS,
    ["Tip: Enterprise firewall (Palo Alto Networks PA-500)",
     "Portlar: 8× 10/100/1000 GE (2× PoE)",
     "Firewall sürəti: 200 Mbps",
     "VPN sürəti: 100 Mbps (IPsec)",
     "Threat Prevention: 100 Mbps",
     "App-ID / User-ID / Content-ID: Dəstəklənir",
     "Menecment: Panorama / Web / CLI",
     "Korpus: 1U, rack-mount"],
    ["Тип: Корпоративный firewall (Palo Alto Networks PA-500)",
     "Порты: 8× 10/100/1000 GE (2× PoE)",
     "Скорость firewall: 200 Мбит/с",
     "Скорость VPN: 100 Мбит/с (IPsec)",
     "Threat Prevention: 100 Мбит/с",
     "App-ID / User-ID / Content-ID: Поддерживается",
     "Управление: Panorama / Web / CLI",
     "Корпус: 1U, монтаж в стойку"],
    ["Type: Enterprise firewall (Palo Alto Networks PA-500)",
     "Ports: 8× 10/100/1000 GE (2× PoE)",
     "Firewall throughput: 200 Mbps",
     "VPN throughput: 100 Mbps (IPsec)",
     "Threat Prevention: 100 Mbps",
     "App-ID / User-ID / Content-ID: Supported",
     "Management: Panorama / Web / CLI",
     "Chassis: 1U, rack-mountable"])

add(80, "CISCO ASA5520", None, 2, 260, MAIN_NETWORK, SUB_FW, "Cisco", COND_ISLENMIS,
    ["Tip: Adaptive Security Appliance (Cisco ASA 5520)",
     "Portlar: 8× 10/100/1000 GE",
     "Firewall sürəti: 450 Mbps",
     "VPN sürəti: 225 Mbps (IPsec), 300 Mbps (SSL)",
     "Eyni vaxtda əlaqələr: 280,000",
     "Aktiv/Passiv HA: Dəstəklənir",
     "Menecment: ASDM (Web) / CLI",
     "Korpus: 1U, rack-mount"],
    ["Тип: Adaptive Security Appliance (Cisco ASA 5520)",
     "Порты: 8× 10/100/1000 GE",
     "Скорость firewall: 450 Мбит/с",
     "Скорость VPN: 225 Мбит/с (IPsec), 300 Мбит/с (SSL)",
     "Одновременных соединений: 280 000",
     "Active/Standby HA: Поддерживается",
     "Управление: ASDM (Web) / CLI",
     "Корпус: 1U, монтаж в стойку"],
    ["Type: Adaptive Security Appliance (Cisco ASA 5520)",
     "Ports: 8× 10/100/1000 GE",
     "Firewall throughput: 450 Mbps",
     "VPN throughput: 225 Mbps (IPsec), 300 Mbps (SSL)",
     "Concurrent connections: 280,000",
     "Active/Standby HA: Supported",
     "Management: ASDM (Web) / CLI",
     "Chassis: 1U, rack-mountable"])

add(81, "CISCO ASA5510", None, 2, 240, MAIN_NETWORK, SUB_FW, "Cisco", COND_ISLENMIS,
    ["Tip: Adaptive Security Appliance (Cisco ASA 5510)",
     "Portlar: 8× 10/100/1000 GE (5× FE + 3× GE)",
     "Firewall sürəti: 300 Mbps",
     "VPN sürəti: 170 Mbps (IPsec), 250 Mbps (SSL)",
     "Eyni vaxtda əlaqələr: 130,000",
     "Menecment: ASDM (Web) / CLI",
     "Korpus: 1U, rack-mount"],
    ["Тип: Adaptive Security Appliance (Cisco ASA 5510)",
     "Порты: 8× 10/100/1000 GE (5× FE + 3× GE)",
     "Скорость firewall: 300 Мбит/с",
     "Скорость VPN: 170 Мбит/с (IPsec), 250 Мбит/с (SSL)",
     "Одновременных соединений: 130 000",
     "Управление: ASDM (Web) / CLI",
     "Корпус: 1U, монтаж в стойку"],
    ["Type: Adaptive Security Appliance (Cisco ASA 5510)",
     "Ports: 8× 10/100/1000 GE (5× FE + 3× GE)",
     "Firewall throughput: 300 Mbps",
     "VPN throughput: 170 Mbps (IPsec), 250 Mbps (SSL)",
     "Concurrent connections: 130,000",
     "Management: ASDM (Web) / CLI",
     "Chassis: 1U, rack-mountable"])

# ============ VoIP və IP telefonlar (yeni) ============
SUB_VOIP = "VoIP və IP telefonlar"

add(7, "LINKSYS SPA3102-NA", "745883569519", 5, 140, MAIN_NETWORK, SUB_VOIP, "Linksys", COND_YENI,
    ["Tip: VoIP ATA şlüz (analoq telefon + PSTN)",
     "Portlar: 1× FXS (analoq telefon) + 1× FXO (PSTN)",
     "VoIP xidmətləri: SIP 2.0",
     "Kodaklar: G.711, G.726, G.729a, G.723",
     "Fax: T.38",
     "Əlaqə: 2× 10/100 Ethernet"],
    ["Тип: VoIP ATA шлюз (аналоговый телефон + PSTN)",
     "Порты: 1× FXS (аналоговый телефон) + 1× FXO (PSTN)",
     "VoIP-протокол: SIP 2.0",
     "Кодеки: G.711, G.726, G.729a, G.723",
     "Факс: T.38",
     "Связь: 2× 10/100 Ethernet"],
    ["Type: VoIP ATA gateway (analog phone + PSTN)",
     "Ports: 1× FXS (analog phone) + 1× FXO (PSTN)",
     "VoIP protocol: SIP 2.0",
     "Codecs: G.711, G.726, G.729a, G.723",
     "Fax: T.38",
     "Connectivity: 2× 10/100 Ethernet"])

add(10, "CISCO IP PHONE CP-7921-A-K9", None, 3, 130, MAIN_NETWORK, SUB_VOIP, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz (Wi-Fi) IP telefon (Cisco 7921G)",
     "Əlaqə: Wi-Fi 802.11g (2.4 GHz)",
     "Xətlər: 6 (SIP)",
     "Ekran: 2.0\" (320×240)",
     "Batareya: Çıxarıla bilən (Li-Ion)",
     "Səs: Full-duplex, HD",
     "Təhlükəsizlik: 802.1X, WPA/WPA2"],
    ["Тип: Беспроводной (Wi-Fi) IP-телефон (Cisco 7921G)",
     "Связь: Wi-Fi 802.11g (2.4 ГГц)",
     "Линий: 6 (SIP)",
     "Экран: 2.0\" (320×240)",
     "Аккумулятор: Съёмный (Li-Ion)",
     "Аудио: Full-duplex, HD",
     "Безопасность: 802.1X, WPA/WPA2"],
    ["Type: Wireless (Wi-Fi) IP phone (Cisco 7921G)",
     "Connectivity: Wi-Fi 802.11g (2.4 GHz)",
     "Lines: 6 (SIP)",
     "Display: 2.0\" (320×240)",
     "Battery: Removable (Li-Ion)",
     "Audio: Full-duplex, HD",
     "Security: 802.1X, WPA/WPA2"])

add(11, "CISCO IP PHONE CP-7925G-A-K9", None, 7, 140, MAIN_NETWORK, SUB_VOIP, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz (Wi-Fi) IP telefon (Cisco 7925G)",
     "Əlaqə: Wi-Fi 802.11a/b/g",
     "Xətlər: 6 (SIP)",
     "Ekran: 2.83\" (QVG, 320×240)",
     "Batareya: Çıxarıla bilən (standart/yüksək tutumlu)",
     "Səs: HD səs, səs-küy azaldılması",
     "Təhlükəsizlik: 802.1X, WPA/WPA2, VPN"],
    ["Тип: Беспроводной (Wi-Fi) IP-телефон (Cisco 7925G)",
     "Связь: Wi-Fi 802.11a/b/g",
     "Линий: 6 (SIP)",
     "Экран: 2.83\" (QVGA, 320×240)",
     "Аккумулятор: Съёмный (стандартный/увеличенный)",
     "Аудио: HD-звук, шумоподавление",
     "Безопасность: 802.1X, WPA/WPA2, VPN"],
    ["Type: Wireless (Wi-Fi) IP phone (Cisco 7925G)",
     "Connectivity: Wi-Fi 802.11a/b/g",
     "Lines: 6 (SIP)",
     "Display: 2.83\" (QVGA, 320×240)",
     "Battery: Removable (standard/high capacity)",
     "Audio: HD voice, noise reduction",
     "Security: 802.1X, WPA/WPA2, VPN"])

add(12, "CISCO SPA302D", None, 3, 80, MAIN_NETWORK, SUB_VOIP, "Cisco", COND_ISLENMIS,
    ["Tip: DECT IP telefon (Cisco SPA302D, baza + qulaqlıq)",
     "Əlaqə: DECT 6.0 + Ethernet (baza)",
     "Xətlər: 1 (SIP)",
     "Baza portları: 1× 10/100 Ethernet",
     "Kodaklar: G.711, G.726, G.729",
     "Funksiyalar: Konfrans, interkom"],
    ["Тип: DECT IP-телефон (Cisco SPA302D, база + трубка)",
     "Связь: DECT 6.0 + Ethernet (база)",
     "Линий: 1 (SIP)",
     "Порты базы: 1× 10/100 Ethernet",
     "Кодеки: G.711, G.726, G.729",
     "Функции: Конференция, интерком"],
    ["Type: DECT IP phone (Cisco SPA302D, base + handset)",
     "Connectivity: DECT 6.0 + Ethernet (base)",
     "Lines: 1 (SIP)",
     "Base ports: 1× 10/100 Ethernet",
     "Codecs: G.711, G.726, G.729",
     "Features: Conference, intercom"])

add(13, "CISCO SPA232D", None, 3, 95, MAIN_NETWORK, SUB_VOIP, "Cisco", COND_ISLENMIS,
    ["Tip: VoIP ATA + DECT baza (Cisco SPA232D)",
     "Portlar: 1× FXS + 1× FXO + 1× 10/100 Ethernet",
     "Əlaqə: DECT 6.0 (2 qulaqlıq dəstəyi)",
     "Xətlər: 2 (SIP)",
     "Router: NAT, DHCP",
     "Kodaklar: G.711, G.726, G.729"],
    ["Тип: VoIP ATA + DECT база (Cisco SPA232D)",
     "Порты: 1× FXS + 1× FXO + 1× 10/100 Ethernet",
     "Связь: DECT 6.0 (поддержка 2 трубок)",
     "Линий: 2 (SIP)",
     "Роутер: NAT, DHCP",
     "Кодеки: G.711, G.726, G.729"],
    ["Type: VoIP ATA + DECT base (Cisco SPA232D)",
     "Ports: 1× FXS + 1× FXO + 1× 10/100 Ethernet",
     "Connectivity: DECT 6.0 (up to 2 handsets)",
     "Lines: 2 (SIP)",
     "Router: NAT, DHCP",
     "Codecs: G.711, G.726, G.729"])

add(14, "GRANDSTREAM DP750", None, 1, 120, MAIN_NETWORK, SUB_VOIP, "Grandstream", COND_ISLENMIS,
    ["Tip: DECT baza stansiyası (Grandstream DP750)",
     "Qulaqlıq dəstəyi: 5-ə qədər DP720/DP722",
     "Eyni vaxtda zənglər: 5",
     "SIP xidmətləri: 5",
     "Əlaqə: 1× 10/100 Ethernet (PoE dəstəyi)",
     "Təhlükəsizlik: TLS, SRTP",
     "Konfrans: 3 yollu"],
    ["Тип: Базовая станция DECT (Grandstream DP750)",
     "Поддержка трубок: до 5 DP720/DP722",
     "Одновременных звонков: 5",
     "SIP-аккаунтов: 5",
     "Связь: 1× 10/100 Ethernet (поддержка PoE)",
     "Безопасность: TLS, SRTP",
     "Конференция: 3-сторонняя"],
    ["Type: DECT base station (Grandstream DP750)",
     "Handset support: up to 5 DP720/DP722",
     "Concurrent calls: 5",
     "SIP accounts: 5",
     "Connectivity: 1× 10/100 Ethernet (PoE support)",
     "Security: TLS, SRTP",
     "Conference: 3-way"])

add(15, "GRANDSTREAM DP720 DECT", None, 1, 135, MAIN_NETWORK, SUB_VOIP, "Grandstream", COND_ISLENMIS,
    ["Tip: DECT qulaqlıq (Grandstream DP720)",
     "Uyğunluq: DP750 baza stansiyası ilə",
     "Ekran: 1.8\" (128×160)",
     "Səs: HD (G.722)",
     "Funksiyalar: Zəng siyahıları, telefon kitabçası, interkom",
     "Batareya: Li-Ion (8 saata qədər danışıq)",
     "Təhlükəsizlik: TLS, SRTP"],
    ["Тип: DECT-трубка (Grandstream DP720)",
     "Совместимость: с базовой станцией DP750",
     "Экран: 1.8\" (128×160)",
     "Аудио: HD (G.722)",
     "Функции: Списки звонков, телефонная книга, интерком",
     "Аккумулятор: Li-Ion (до 8 часов разговора)",
     "Безопасность: TLS, SRTP"],
    ["Type: DECT handset (Grandstream DP720)",
     "Compatibility: works with DP750 base station",
     "Display: 1.8\" (128×160)",
     "Audio: HD (G.722)",
     "Features: Call lists, phonebook, intercom",
     "Battery: Li-Ion (up to 8 hours talk time)",
     "Security: TLS, SRTP"])

add(16, "CISCO CP8821-K9 V07", None, 1, 275, MAIN_NETWORK, SUB_VOIP, "Cisco", COND_ISLENMIS,
    ["Tip: Simsiz (Wi-Fi) IP telefon (Cisco 8821)",
     "Əlaqə: Wi-Fi 802.11a/b/g/n (2.4/5 GHz)",
     "Xətlər: 6 (SIP)",
     "Ekran: 2.4\" (320×240)",
     "Batareya: Çıxarıla bilən (Li-Ion, standart/yüksək tutumlu)",
     "Səs: HD, səs-küy azaldılması, PTT",
     "Qoruma: IP54 (toz/su sıçramasına davamlı)"],
    ["Тип: Беспроводной (Wi-Fi) IP-телефон (Cisco 8821)",
     "Связь: Wi-Fi 802.11a/b/g/n (2.4/5 ГГц)",
     "Линий: 6 (SIP)",
     "Экран: 2.4\" (320×240)",
     "Аккумулятор: Съёмный (Li-Ion, стандартный/увеличенный)",
     "Аудио: HD, шумоподавление, PTT",
     "Защита: IP54 (пыль/брызги)"],
    ["Type: Wireless (Wi-Fi) IP phone (Cisco 8821)",
     "Connectivity: Wi-Fi 802.11a/b/g/n (2.4/5 GHz)",
     "Lines: 6 (SIP)",
     "Display: 2.4\" (320×240)",
     "Battery: Removable (Li-Ion, standard/high capacity)",
     "Audio: HD, noise reduction, PTT",
     "Protection: IP54 (dust/splash resistant)"])

add(83, "CISCO IP PHONE 7861", None, 0, 320, MAIN_NETWORK, SUB_VOIP, "Cisco", COND_ISLENMIS,
    ["Tip: Analoq telefon (Cisco 7861)",
     "Xətlər: 6",
     "Port: 1× RJ11 (analoq xətt)",
     "Ekran: 2 dərəcəli (LCD)",
     "Səs: Full-duplex, səs-küy azaldılması",
     "Güc: Analoq xəttdən (DC) / enerji adapteri"],
    ["Тип: Аналоговый телефон (Cisco 7861)",
     "Линий: 6",
     "Порт: 1× RJ11 (аналоговая линия)",
     "Экран: 2-строчный (LCD)",
     "Аудио: Full-duplex, шумоподавление",
     "Питание: От аналоговой линии (DC) / адаптер"],
    ["Type: Analog phone (Cisco 7861)",
     "Lines: 6",
     "Port: 1× RJ11 (analog line)",
     "Display: 2-line (LCD)",
     "Audio: Full-duplex, noise reduction",
     "Power: From analog line (DC) / adapter"])

# ============ SERVER (yeni alt kateqoriya) ============
SUB_SERVER = "Serverlər"

add(56, "HP DL380 GEN9", None, 2, 500, MAIN_SERVER, SUB_SERVER, "HP", COND_ISLENMIS,
    ["Tip: Rack server (2U, HP ProLiant DL380 Gen9)",
     "Prosessor: 2× Intel Xeon E5 v3/v4 (LGA2011-3)",
     "Yaddaş: 24 DIMM, DDR4 (1.5 TB-a qədər)",
     "Sürücü yuvası: 8× LFF / 24× SFF",
     "Disk kontroller: Smart Array P440ar",
     "Şəbəkə: 4× 1GbE (daxili)",
     "Güc: 2× 800W hot-plug (redundant)",
     "İdarəetmə: iLO4 (remote management)"],
    ["Тип: Стоечный сервер (2U, HP ProLiant DL380 Gen9)",
     "Процессор: 2× Intel Xeon E5 v3/v4 (LGA2011-3)",
     "Память: 24 DIMM, DDR4 (до 1.5 ТБ)",
     "Отсеки для дисков: 8× LFF / 24× SFF",
     "Дисковый контроллер: Smart Array P440ar",
     "Сеть: 4× 1GbE (встроенные)",
     "Питание: 2× 800W hot-plug (резервирование)",
     "Управление: iLO4 (удалённое управление)"],
    ["Type: Rack server (2U, HP ProLiant DL380 Gen9)",
     "Processor: 2× Intel Xeon E5 v3/v4 (LGA2011-3)",
     "Memory: 24 DIMM, DDR4 (up to 1.5 TB)",
     "Drive bays: 8× LFF / 24× SFF",
     "Disk controller: Smart Array P440ar",
     "Networking: 4× 1GbE (built-in)",
     "Power: 2× 800W hot-plug (redundant)",
     "Management: iLO4 (remote management)"])

add(57, "HP DL360 GEN9", None, 1, 500, MAIN_SERVER, SUB_SERVER, "HP", COND_ISLENMIS,
    ["Tip: Rack server (1U, HP ProLiant DL360 Gen9)",
     "Prosessor: 2× Intel Xeon E5 v3/v4",
     "Yaddaş: 24 DIMM, DDR4 (768 GB-a qədər)",
     "Sürücü yuvası: 8× SFF / 4× LFF",
     "Disk kontroller: Smart Array P440ar",
     "Şəbəkə: 4× 1GbE",
     "Güc: 2× 500W hot-plug (redundant)",
     "İdarəetmə: iLO4"],
    ["Тип: Стоечный сервер (1U, HP ProLiant DL360 Gen9)",
     "Процессор: 2× Intel Xeon E5 v3/v4",
     "Память: 24 DIMM, DDR4 (до 768 ГБ)",
     "Отсеки для дисков: 8× SFF / 4× LFF",
     "Дисковый контроллер: Smart Array P440ar",
     "Сеть: 4× 1GbE",
     "Питание: 2× 500W hot-plug (резервирование)",
     "Управление: iLO4"],
    ["Type: Rack server (1U, HP ProLiant DL360 Gen9)",
     "Processor: 2× Intel Xeon E5 v3/v4",
     "Memory: 24 DIMM, DDR4 (up to 768 GB)",
     "Drive bays: 8× SFF / 4× LFF",
     "Disk controller: Smart Array P440ar",
     "Networking: 4× 1GbE",
     "Power: 2× 500W hot-plug (redundant)",
     "Management: iLO4"])

add(58, "HP DL380 GEN8", None, 1, 500, MAIN_SERVER, SUB_SERVER, "HP", COND_ISLENMIS,
    ["Tip: Rack server (2U, HP ProLiant DL380 Gen8)",
     "Prosessor: 2× Intel Xeon E5 v1/v2 (LGA2011)",
     "Yaddaş: 24 DIMM, DDR3 (768 GB-a qədər)",
     "Sürücü yuvası: 8× LFF / 25× SFF",
     "Disk kontroller: Smart Array P420i",
     "Şəbəkə: 4× 1GbE",
     "Güc: 2× 750W hot-plug (redundant)",
     "İdarəetmə: iLO4"],
    ["Тип: Стоечный сервер (2U, HP ProLiant DL380 Gen8)",
     "Процессор: 2× Intel Xeon E5 v1/v2 (LGA2011)",
     "Память: 24 DIMM, DDR3 (до 768 ГБ)",
     "Отсеки для дисков: 8× LFF / 25× SFF",
     "Дисковый контроллер: Smart Array P420i",
     "Сеть: 4× 1GbE",
     "Питание: 2× 750W hot-plug (резервирование)",
     "Управление: iLO4"],
    ["Type: Rack server (2U, HP ProLiant DL380 Gen8)",
     "Processor: 2× Intel Xeon E5 v1/v2 (LGA2011)",
     "Memory: 24 DIMM, DDR3 (up to 768 GB)",
     "Drive bays: 8× LFF / 25× SFF",
     "Disk controller: Smart Array P420i",
     "Networking: 4× 1GbE",
     "Power: 2× 750W hot-plug (redundant)",
     "Management: iLO4"])

# ------------------------------------------------------------ workbook ----
HEADERS = [
    ("№", 6),
    ("Model", 30),
    ("Barkod", 16),
    ("Vəziyyəti", 12),
    ("Qty", 6),
    ("Qiymət (AZN) — endirimli", 18),
    ("Köhnə qiymət (AZN)", 18),
    ("Əsas kateqoriya", 24),
    ("Alt kateqoriya", 22),
    ("Brend", 12),
    ("Xüsusiyyətlər (AZ)", 44),
    ("Xüsusiyyətlər (RU)", 44),
    ("Xüsusiyyətlər (EN)", 44),
    ("Şəkil linkləri", 40),
]

CATEGORY_SHEET = [
    (MAIN_NETWORK, "sebeke-avadanliqlari", "Access Point", "access-point", "Mövcud"),
    (MAIN_NETWORK, "sebeke-avadanliqlari", "Wi-Fi kontroller", "wi-fi-kontroller", "YENİ — yaradılmalıdır"),
    (MAIN_NETWORK, "sebeke-avadanliqlari", "Kommutator", "kommutator", "Mövcud"),
    (MAIN_NETWORK, "sebeke-avadanliqlari", "Router", "router", "Mövcud"),
    (MAIN_NETWORK, "sebeke-avadanliqlari", "Firewall", "firewall", "YENİ — yaradılmalıdır"),
    (MAIN_NETWORK, "sebeke-avadanliqlari", "VoIP və IP telefonlar", "voip-ip-telefonlar", "YENİ — yaradılmalıdır"),
    (MAIN_SERVER, "server", "Serverlər", "serverler", "YENİ — yaradılmalıdır"),
]


def build_wb():
    wb = Workbook()

    thin = Side(style="thin", color="D0D0D0")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    title_font = Font(name="Calibri", size=14, bold=True, color="1F4E79")
    wrap = Alignment(vertical="top", wrap_text=True)
    center = Alignment(horizontal="center", vertical="top", wrap_text=True)

    # ---------- Sheet 1: Məhsullar ----------
    ws = wb.active
    ws.title = "Məhsullar"

    ws["A1"] = "Diger (Cisco / HP / Aruba / Fortinet / Palo Alto / TP-Link) — Məhsul siyahısı (24.08.2026) | IT Market üçün"
    ws["A1"].font = title_font
    ws["A2"] = (
        "Qiymət (AZN) hazırkı endirimli qiymətdir və dəyişmir. Köhnə qiymət = Qiymət + 50 AZN. "
        "Vəziyyəti: \"Yeni\" yazılan məhsullar yeni, digərləri işlənmişdir. "
        "RU və EN xüsusiyyətlər lüğət bazasına əlavə olunmaq üçündür."
    )
    ws["A2"].font = Font(name="Calibri", size=10, italic=True, color="555555")

    header_row = 3
    for col, (name, width) in enumerate(HEADERS, start=1):
        cell = ws.cell(row=header_row, column=col, value=name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
        cell.border = border
        ws.column_dimensions[get_column_letter(col)].width = width

    row = header_row + 1
    for num, model, barcode, qty, price, main, sub, brand, cond, az, ru, en in P:
        old_price = round(price + 50, 2)
        values = [
            num, model, barcode or "", cond, qty, price, old_price,
            main, sub, brand,
            "\n".join(az), "\n".join(ru), "\n".join(en), "",
        ]
        for col, v in enumerate(values, start=1):
            cell = ws.cell(row=row, column=col, value=v)
            cell.border = border
            cell.alignment = center if col in (1, 4, 5, 6, 7) else wrap
        row += 1

    ws.freeze_panes = "B4"
    ws.auto_filter.ref = f"A{header_row}:{get_column_letter(len(HEADERS))}{row - 1}"

    # ---------- Sheet 2: Kateqoriyalar ----------
    ws2 = wb.create_sheet("Kateqoriyalar")
    ws2["A1"] = "Saytda mövcud və yeni təklif olunan kateqoriyalar"
    ws2["A1"].font = title_font

    cat_headers = ["Əsas kateqoriya", "Əsas slug", "Alt kateqoriya", "Alt slug", "Status"]
    for col, name in enumerate(cat_headers, start=1):
        cell = ws2.cell(row=3, column=col, value=name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
        cell.border = border
        ws2.column_dimensions[get_column_letter(col)].width = 34

    for r, (main, main_slug, sub, sub_slug, status) in enumerate(CATEGORY_SHEET, start=4):
        for c, v in enumerate([main, main_slug, sub, sub_slug, status], start=1):
            cell = ws2.cell(row=r, column=c, value=v)
            cell.border = border
            cell.alignment = wrap
            if status.startswith("YENİ"):
                cell.fill = PatternFill("solid", fgColor="FFF2CC")
                cell.font = Font(bold=True, color="7F6000")

    ws2.freeze_panes = "A4"

    out = "Sayt üçün 24082026_260812_162518 -Diger.xlsx"
    wb.save(out)
    print(f"OK: {out} ({len(P)} products)")


if __name__ == "__main__":
    build_wb()
