# -*- coding: utf-8 -*-
"""Generate the Konnektronik product Excel for the IT Market site."""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

MAIN_SECURITY = "Təhlükəsizlik avadanlıqları"
MAIN_NETWORK = "Şəbəkə avadanlıqları"

# (num, model, barcode, qty, price, main, sub, brand, specs_az, specs_ru, specs_en)
PRODUCTS = [
    (
        2, "TP-Link VIGI C320I", "4897098688939", 3, 55.99,
        MAIN_SECURITY, "IP kamera", "TP-Link",
        [
            "Tip: IP kamera (xarici, bullet)",
            "Sensor: 1/3\" Progressive Scan CMOS",
            "Qətnamə: 2 MP (1920×1080)",
            "Lens: 2.8/4/6 mm, F2.2–F2.0",
            "Gecə görüntüsü: IR, 30 m (850 nm)",
            "Video sıxlaşdırma: H.265+/H.265/H.264+/H.264",
            "Smart deteksiya: İnsan və nəqliyyat vasitəsi tanıma",
            "Qoruma: IP67",
            "Mikrofon: Daxili",
            "Güc: PoE (IEEE 802.3af/at)",
            "ONVIF: Dəstəklənir",
            "İş temperaturu: -30°C...60°C",
            "Ölçü: 78.5×188×71.6 mm",
        ],
        [
            "Тип: IP-камера (уличная, пуля)",
            "Матрица: 1/3\" Progressive Scan CMOS",
            "Разрешение: 2 Мп (1920×1080)",
            "Объектив: 2.8/4/6 мм, F2.2–F2.0",
            "Ночное видение: ИК, 30 м (850 нм)",
            "Сжатие видео: H.265+/H.265/H.264+/H.264",
            "Умное обнаружение: Распознавание людей и транспорта",
            "Защита: IP67",
            "Микрофон: Встроенный",
            "Питание: PoE (IEEE 802.3af/at)",
            "ONVIF: Поддерживается",
            "Рабочая температура: -30°C...60°C",
            "Размеры: 78.5×188×71.6 мм",
        ],
        [
            "Type: IP camera (outdoor, bullet)",
            "Image sensor: 1/3\" Progressive Scan CMOS",
            "Resolution: 2 MP (1920×1080)",
            "Lens: 2.8/4/6 mm, F2.2–F2.0",
            "Night vision: IR, 30 m (850 nm)",
            "Video compression: H.265+/H.265/H.264+/H.264",
            "Smart detection: Human and vehicle recognition",
            "Protection: IP67",
            "Microphone: Built-in",
            "Power: PoE (IEEE 802.3af/at)",
            "ONVIF: Supported",
            "Operating temperature: -30°C...60°C",
            "Dimensions: 78.5×188×71.6 mm",
        ],
    ),
    (
        3, "TP-Link VIGI C220I", "4897098688861", 2, 71.99,
        MAIN_SECURITY, "IP kamera", "TP-Link",
        [
            "Tip: IP kamera (dome)",
            "Sensor: 1/3\" Progressive Scan CMOS",
            "Qətnamə: 2 MP (1920×1080)",
            "Lens: 2.8/4 mm, F2.2–F2.0",
            "Gecə görüntüsü: IR, 30 m (850 nm)",
            "Video sıxlaşdırma: H.265+/H.265/H.264+/H.264",
            "Smart deteksiya: İnsan və nəqliyyat vasitəsi tanıma",
            "Qoruma: IP67, IK10 (vandal davamlı)",
            "Mikrofon: Daxili",
            "Güc: PoE (IEEE 802.3af/at)",
            "İş temperaturu: -30°C...60°C",
            "Ölçü: 115×115×86 mm",
        ],
        [
            "Тип: IP-камера (купол)",
            "Матрица: 1/3\" Progressive Scan CMOS",
            "Разрешение: 2 Мп (1920×1080)",
            "Объектив: 2.8/4 мм, F2.2–F2.0",
            "Ночное видение: ИК, 30 м (850 нм)",
            "Сжатие видео: H.265+/H.265/H.264+/H.264",
            "Умное обнаружение: Распознавание людей и транспорта",
            "Защита: IP67, IK10 (антивандальная)",
            "Микрофон: Встроенный",
            "Питание: PoE (IEEE 802.3af/at)",
            "Рабочая температура: -30°C...60°C",
            "Размеры: 115×115×86 мм",
        ],
        [
            "Type: IP camera (dome)",
            "Image sensor: 1/3\" Progressive Scan CMOS",
            "Resolution: 2 MP (1920×1080)",
            "Lens: 2.8/4 mm, F2.2–F2.0",
            "Night vision: IR, 30 m (850 nm)",
            "Video compression: H.265+/H.265/H.264+/H.264",
            "Smart detection: Human and vehicle recognition",
            "Protection: IP67, IK10 (vandal resistant)",
            "Microphone: Built-in",
            "Power: PoE (IEEE 802.3af/at)",
            "Operating temperature: -30°C...60°C",
            "Dimensions: 115×115×86 mm",
        ],
    ),
    (
        4, "TP-Link VIGI C230", "4897098689905", 3, 89.99,
        MAIN_SECURITY, "IP kamera", "TP-Link",
        [
            "Tip: IP kamera (dome, tam rəng)",
            "Sensor: 1/2.8\" Progressive Scan CMOS",
            "Qətnamə: 3 MP (2304×1296)",
            "Lens: 2.8/4 mm, F1.6",
            "Gecə görüntüsü: Tam rəngli (IR + White LED), 30 m",
            "Video sıxlaşdırma: H.265+/H.265/H.264+/H.264",
            "Smart deteksiya: İnsan və nəqliyyat tanıma, hüdud pozulması",
            "Qoruma: IP67, IK10",
            "Mikrofon: Daxili",
            "Güc: 12V DC / PoE (IEEE 802.3af/at)",
            "İş temperaturu: -30°C...60°C",
            "Ölçü: 115×115×86 mm",
        ],
        [
            "Тип: IP-камера (купол, цветная)",
            "Матрица: 1/2.8\" Progressive Scan CMOS",
            "Разрешение: 3 Мп (2304×1296)",
            "Объектив: 2.8/4 мм, F1.6",
            "Ночное видение: Цветное (ИК + белый LED), 30 м",
            "Сжатие видео: H.265+/H.265/H.264+/H.264",
            "Умное обнаружение: Распознавание людей и транспорта, пересечение границы",
            "Защита: IP67, IK10",
            "Микрофон: Встроенный",
            "Питание: 12V DC / PoE (IEEE 802.3af/at)",
            "Рабочая температура: -30°C...60°C",
            "Размеры: 115×115×86 мм",
        ],
        [
            "Type: IP camera (dome, full-color)",
            "Image sensor: 1/2.8\" Progressive Scan CMOS",
            "Resolution: 3 MP (2304×1296)",
            "Lens: 2.8/4 mm, F1.6",
            "Night vision: Full-color (IR + white LED), 30 m",
            "Video compression: H.265+/H.265/H.264+/H.264",
            "Smart detection: Human and vehicle recognition, line crossing",
            "Protection: IP67, IK10",
            "Microphone: Built-in",
            "Power: 12V DC / PoE (IEEE 802.3af/at)",
            "Operating temperature: -30°C...60°C",
            "Dimensions: 115×115×86 mm",
        ],
    ),
    (
        5, "TP-Link VIGI C540", "4897098683781", 2, 171.99,
        MAIN_SECURITY, "IP kamera", "TP-Link",
        [
            "Tip: IP kamera (PTZ, tam rəng, xarici)",
            "Sensor: 1/3\" Progressive Scan CMOS",
            "Qətnamə: 4 MP (2560×1440)",
            "Lens: 4 mm, F1.6",
            "PTZ: Pan 0–350°, Tilt 0–120°",
            "Gecə görüntüsü: Tam rəngli (IR + White LED), 30 m",
            "Video sıxlaşdırma: H.265+/H.265/H.264+/H.264",
            "Səs: İki tərəfli (daxili mikrofon və dinamik)",
            "Yaddaş: microSD, 512 GB-a qədər",
            "Qoruma: IP66",
            "Güc: 12V DC / PoE (IEEE 802.3at)",
            "Smart deteksiya: İnsan tanıma, avto-izləmə, patrol rejimi",
        ],
        [
            "Тип: IP-камера (поворотная, цветная, уличная)",
            "Матрица: 1/3\" Progressive Scan CMOS",
            "Разрешение: 4 Мп (2560×1440)",
            "Объектив: 4 мм, F1.6",
            "PTZ: Pan 0–350°, Tilt 0–120°",
            "Ночное видение: Цветное (ИК + белый LED), 30 м",
            "Сжатие видео: H.265+/H.265/H.264+/H.264",
            "Аудио: Двусторонняя связь (встроенные микрофон и динамик)",
            "Хранилище: microSD, до 512 ГБ",
            "Защита: IP66",
            "Питание: 12V DC / PoE (IEEE 802.3at)",
            "Умное обнаружение: Распознавание людей, автослежение, патрулирование",
        ],
        [
            "Type: IP camera (pan-tilt, full-color, outdoor)",
            "Image sensor: 1/3\" Progressive Scan CMOS",
            "Resolution: 4 MP (2560×1440)",
            "Lens: 4 mm, F1.6",
            "PTZ: Pan 0–350°, Tilt 0–120°",
            "Night vision: Full-color (IR + white LED), 30 m",
            "Video compression: H.265+/H.265/H.264+/H.264",
            "Audio: Two-way (built-in microphone and speaker)",
            "Storage: microSD, up to 512 GB",
            "Protection: IP66",
            "Power: 12V DC / PoE (IEEE 802.3at)",
            "Smart detection: Human recognition, auto-tracking, patrol",
        ],
    ),
    (
        7, "Tapo C410 KIT EU", "8885020620368", 2, 173.99,
        MAIN_SECURITY, "Wi-Fi kameralar", "Tapo",
        [
            "Tip: Simsiz batareyalı kamera dəsti (günəş paneli ilə)",
            "Qətnamə: 2K 3MP (2304×1296)",
            "Batareya: Daxili 5200 mAh (180 günə qədər)",
            "Günəş paneli: Tapo A201 (dəstə daxildir)",
            "Gecə görüntüsü: Tam rəngli (spotlight), 9.1 m",
            "Görmə bucağı: 125° diaqonal",
            "Video sıxlaşdırma: H.264",
            "AI deteksiya: İnsan tanıma (pulsuz)",
            "Səs: İki tərəfli, səs-küy azaldılması ilə",
            "Sirena: 94 dB",
            "Yaddaş: microSD, 512 GB-a qədər",
            "Qoruma: IP65",
            "Əlaqə: Wi-Fi 2.4 GHz",
        ],
        [
            "Тип: Беспроводная камера с аккумулятором (с солнечной панелью)",
            "Разрешение: 2K 3Мп (2304×1296)",
            "Аккумулятор: Встроенный 5200 мАч (до 180 дней)",
            "Солнечная панель: Tapo A201 (в комплекте)",
            "Ночное видение: Цветное (прожектор), 9.1 м",
            "Угол обзора: 125° диагональ",
            "Сжатие видео: H.264",
            "ИИ-обнаружение: Распознавание людей (бесплатно)",
            "Аудио: Двусторонняя связь с шумоподавлением",
            "Сирена: 94 дБ",
            "Хранилище: microSD, до 512 ГБ",
            "Защита: IP65",
            "Подключение: Wi-Fi 2.4 ГГц",
        ],
        [
            "Type: Wireless battery camera kit (with solar panel)",
            "Resolution: 2K 3MP (2304×1296)",
            "Battery: Built-in 5200 mAh (up to 180 days)",
            "Solar panel: Tapo A201 (included in kit)",
            "Night vision: Full-color (spotlight), 9.1 m",
            "Field of view: 125° diagonal",
            "Video compression: H.264",
            "AI detection: Human recognition (free)",
            "Audio: Two-way with noise cancellation",
            "Siren: 94 dB",
            "Storage: microSD, up to 512 GB",
            "Protection: IP65",
            "Connectivity: Wi-Fi 2.4 GHz",
        ],
    ),
    (
        8, "Tapo C501GW", "8885020621037", 10, 163.99,
        MAIN_SECURITY, "Wi-Fi kameralar", "Tapo",
        [
            "Tip: Xarici PTZ 4G LTE kamera",
            "Qətnamə: 1080p (1920×1080)",
            "Əlaqə: 4G LTE (SIM kart) / LAN (Ethernet)",
            "PTZ: 360° üfüqi, 139° şaquli",
            "Gecə görüntüsü: Tam rəngli (spotlight), 29.8 m",
            "Video sıxlaşdırma: H.264",
            "AI deteksiya: İnsan, ev heyvanı və nəqliyyat tanıma",
            "Səs: İki tərəfli",
            "Yaddaş: microSD, 512 GB-a qədər + bulud",
            "Qoruma: IP66",
            "Güc: 12V DC / PoE (IEEE 802.3af/at)",
            "LTE bantları: FDD B1/3/5/7/8/20/28, TDD B38/40/41",
        ],
        [
            "Тип: Уличная поворотная 4G LTE камера",
            "Разрешение: 1080p (1920×1080)",
            "Подключение: 4G LTE (SIM-карта) / LAN (Ethernet)",
            "PTZ: 360° по горизонтали, 139° по вертикали",
            "Ночное видение: Цветное (прожектор), 29.8 м",
            "Сжатие видео: H.264",
            "ИИ-обнаружение: Распознавание людей, животных и транспорта",
            "Аудио: Двусторонняя связь",
            "Хранилище: microSD, до 512 ГБ + облако",
            "Защита: IP66",
            "Питание: 12V DC / PoE (IEEE 802.3af/at)",
            "Диапазоны LTE: FDD B1/3/5/7/8/20/28, TDD B38/40/41",
        ],
        [
            "Type: Outdoor pan-tilt 4G LTE camera",
            "Resolution: 1080p (1920×1080)",
            "Connectivity: 4G LTE (SIM card) / LAN (Ethernet)",
            "PTZ: 360° horizontal, 139° vertical",
            "Night vision: Full-color (spotlight), 29.8 m",
            "Video compression: H.264",
            "AI detection: Human, pet and vehicle recognition",
            "Audio: Two-way",
            "Storage: microSD, up to 512 GB + cloud",
            "Protection: IP66",
            "Power: 12V DC / PoE (IEEE 802.3af/at)",
            "LTE bands: FDD B1/3/5/7/8/20/28, TDD B38/40/41",
        ],
    ),
    (
        10, "Mercusys MR60X AX1500", "6957939001223", 2, 55.99,
        MAIN_NETWORK, "Router", "Mercusys",
        [
            "Tip: Wi-Fi 6 router",
            "Wi-Fi sinfi: AX1500 (1201 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standart: IEEE 802.11ax/ac/a/b/g/n",
            "Portlar: 1× Gigabit WAN + 2× Gigabit LAN",
            "Antenalar: 4× 5 dBi",
            "Təhlükəsizlik: WPA/WPA2/WPA3",
            "Qonaq şəbəkəsi: 2.4 GHz + 5 GHz",
            "EasyMesh: Dəstəklənir",
            "OFDMA / MU-MIMO: Dəstəklənir",
            "VPN: Server/client dəstəyi",
            "Ölçü: 175.6×157.2×45 mm",
        ],
        [
            "Тип: Роутер Wi-Fi 6",
            "Класс Wi-Fi: AX1500 (1201 Мбит/с 5 ГГц + 300 Мбит/с 2.4 ГГц)",
            "Стандарт: IEEE 802.11ax/ac/a/b/g/n",
            "Порты: 1× Gigabit WAN + 2× Gigabit LAN",
            "Антенны: 4× 5 дБи",
            "Безопасность: WPA/WPA2/WPA3",
            "Гостевая сеть: 2.4 ГГц + 5 ГГц",
            "EasyMesh: Поддерживается",
            "OFDMA / MU-MIMO: Поддерживается",
            "VPN: Поддержка сервера/клиента",
            "Размеры: 175.6×157.2×45 мм",
        ],
        [
            "Type: Wi-Fi 6 router",
            "Wi-Fi class: AX1500 (1201 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standard: IEEE 802.11ax/ac/a/b/g/n",
            "Ports: 1× Gigabit WAN + 2× Gigabit LAN",
            "Antennas: 4× 5 dBi",
            "Security: WPA/WPA2/WPA3",
            "Guest network: 2.4 GHz + 5 GHz",
            "EasyMesh: Supported",
            "OFDMA / MU-MIMO: Supported",
            "VPN: Server/client support",
            "Dimensions: 175.6×157.2×45 mm",
        ],
    ),
    (
        11, "Mercusys AC12 AC1200", "6957939000479", 52, 39.99,
        MAIN_NETWORK, "Router", "Mercusys",
        [
            "Tip: Dual band router",
            "Wi-Fi sinfi: AC1200 (867 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standart: IEEE 802.11ac/a/b/g/n",
            "Portlar: 1× 10/100 Mbps WAN + 4× 10/100 Mbps LAN",
            "Antenalar: 4× 5 dBi",
            "Təhlükəsizlik: WPA-PSK/WPA2-PSK",
            "Qonaq şəbəkəsi: 2.4 GHz + 5 GHz",
            "IPv6: Dəstəklənir",
            "IPTV: Dəstəklənir",
            "Ölçü: 222×140×32 mm",
        ],
        [
            "Тип: Двухдиапазонный роутер",
            "Класс Wi-Fi: AC1200 (867 Мбит/с 5 ГГц + 300 Мбит/с 2.4 ГГц)",
            "Стандарт: IEEE 802.11ac/a/b/g/n",
            "Порты: 1× 10/100 Мбит/с WAN + 4× 10/100 Мбит/с LAN",
            "Антенны: 4× 5 дБи",
            "Безопасность: WPA-PSK/WPA2-PSK",
            "Гостевая сеть: 2.4 ГГц + 5 ГГц",
            "IPv6: Поддерживается",
            "IPTV: Поддерживается",
            "Размеры: 222×140×32 мм",
        ],
        [
            "Type: Dual-band router",
            "Wi-Fi class: AC1200 (867 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standard: IEEE 802.11ac/a/b/g/n",
            "Ports: 1× 10/100 Mbps WAN + 4× 10/100 Mbps LAN",
            "Antennas: 4× 5 dBi",
            "Security: WPA-PSK/WPA2-PSK",
            "Guest network: 2.4 GHz + 5 GHz",
            "IPv6: Supported",
            "IPTV: Supported",
            "Dimensions: 222×140×32 mm",
        ],
    ),
    (
        12, "Mercusys MR30G", "6957939000615", 21, 44.99,
        MAIN_NETWORK, "Router", "Mercusys",
        [
            "Tip: AC1200 Gigabit router",
            "Wi-Fi sinfi: AC1200 (867 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standart: IEEE 802.11ac/a/b/g/n",
            "Portlar: 1× Gigabit WAN + 2× Gigabit LAN",
            "Antenalar: 4× 5 dBi",
            "MU-MIMO: Dəstəklənir",
            "Rejim: Router / Access Point",
            "IPv6: Dəstəklənir",
            "Qonaq şəbəkəsi: 2.4 GHz + 5 GHz",
            "Təhlükəsizlik: WPA-PSK/WPA2-PSK",
            "Ölçü: 159.7×125.9×37.1 mm",
        ],
        [
            "Тип: Гигабитный роутер AC1200",
            "Класс Wi-Fi: AC1200 (867 Мбит/с 5 ГГц + 300 Мбит/с 2.4 ГГц)",
            "Стандарт: IEEE 802.11ac/a/b/g/n",
            "Порты: 1× Gigabit WAN + 2× Gigabit LAN",
            "Антенны: 4× 5 дБи",
            "MU-MIMO: Поддерживается",
            "Режим: Роутер / Точка доступа",
            "IPv6: Поддерживается",
            "Гостевая сеть: 2.4 ГГц + 5 ГГц",
            "Безопасность: WPA-PSK/WPA2-PSK",
            "Размеры: 159.7×125.9×37.1 мм",
        ],
        [
            "Type: AC1200 Gigabit router",
            "Wi-Fi class: AC1200 (867 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standard: IEEE 802.11ac/a/b/g/n",
            "Ports: 1× Gigabit WAN + 2× Gigabit LAN",
            "Antennas: 4× 5 dBi",
            "MU-MIMO: Supported",
            "Mode: Router / Access Point",
            "IPv6: Supported",
            "Guest network: 2.4 GHz + 5 GHz",
            "Security: WPA-PSK/WPA2-PSK",
            "Dimensions: 159.7×125.9×37.1 mm",
        ],
    ),
    (
        13, "Mercusys ME30", "6957939000516", 3, 49.99,
        MAIN_NETWORK, "Wi-Fi gücləndirici", "Mercusys",
        [
            "Tip: Wi-Fi gücləndirici (range extender)",
            "Wi-Fi sinfi: AC1200 (867 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standart: IEEE 802.11a/n/ac 5 GHz, 802.11b/g/n 2.4 GHz",
            "Port: 1× 10/100 Mbps RJ45",
            "Antenalar: 2× xarici",
            "Rejim: Range Extender / Access Point",
            "EasyMesh: Dəstəklənir",
            "WPS: Bir toxunuşla qurulum",
            "Göstərici: Çoxrəngli siqnal LED",
            "Güc istehlakı: 9.2 W",
            "Ölçü: 112×84.7×39 mm",
        ],
        [
            "Тип: Усилитель Wi-Fi (репитер)",
            "Класс Wi-Fi: AC1200 (867 Мбит/с 5 ГГц + 300 Мбит/с 2.4 ГГц)",
            "Стандарт: IEEE 802.11a/n/ac 5 ГГц, 802.11b/g/n 2.4 ГГц",
            "Порт: 1× 10/100 Мбит/с RJ45",
            "Антенны: 2× внешние",
            "Режим: Репитер / Точка доступа",
            "EasyMesh: Поддерживается",
            "WPS: Настройка в одно касание",
            "Индикатор: Многоцветный светодиод сигнала",
            "Потребляемая мощность: 9.2 Вт",
            "Размеры: 112×84.7×39 мм",
        ],
        [
            "Type: Wi-Fi range extender",
            "Wi-Fi class: AC1200 (867 Mbps 5 GHz + 300 Mbps 2.4 GHz)",
            "Standard: IEEE 802.11a/n/ac 5 GHz, 802.11b/g/n 2.4 GHz",
            "Port: 1× 10/100 Mbps RJ45",
            "Antennas: 2× external",
            "Mode: Range Extender / Access Point",
            "EasyMesh: Supported",
            "WPS: One-touch setup",
            "Indicator: Multi-color signal LED",
            "Power consumption: 9.2 W",
            "Dimensions: 112×84.7×39 mm",
        ],
    ),
    (
        14, "TP-Link TL-SG1008P(UN)", "6935364021160", 3, 131.99,
        MAIN_NETWORK, "Kommutator", "TP-Link",
        [
            "Tip: Kommutator (idarəolunmaz)",
            "Portlar: 8× 10/100/1000 Mbps (1–4 PoE+)",
            "PoE büdcəsi: 64 W (port başına 30 W-a qədər)",
            "PoE standartı: IEEE 802.3af/at",
            "Kommutasiya tutumu: 16 Gbps",
            "Extend Mode: 250 m-ə qədər (1–2 port)",
            "PoE Auto Recovery: Bəli",
            "MAC cədvəli: 4K",
            "Jumbo frame: 16 KB",
            "Fan: Fanless (səssiz)",
            "Ölçü: 171×98×27 mm",
        ],
        [
            "Тип: Коммутатор (неуправляемый)",
            "Порты: 8× 10/100/1000 Мбит/с (1–4 PoE+)",
            "PoE-бюджет: 64 Вт (до 30 Вт на порт)",
            "Стандарт PoE: IEEE 802.3af/at",
            "Коммутационная способность: 16 Гбит/с",
            "Extend Mode: до 250 м (порты 1–2)",
            "PoE Auto Recovery: Да",
            "MAC-таблица: 4K",
            "Jumbo frame: 16 КБ",
            "Вентилятор: Нет (бесшумный)",
            "Размеры: 171×98×27 мм",
        ],
        [
            "Type: Switch (unmanaged)",
            "Ports: 8× 10/100/1000 Mbps (1–4 PoE+)",
            "PoE budget: 64 W (up to 30 W per port)",
            "PoE standard: IEEE 802.3af/at",
            "Switching capacity: 16 Gbps",
            "Extend Mode: up to 250 m (ports 1–2)",
            "PoE Auto Recovery: Yes",
            "MAC table: 4K",
            "Jumbo frame: 16 KB",
            "Fan: Fanless (silent)",
            "Dimensions: 171×98×27 mm",
        ],
    ),
    (
        15, "TP-Link CPE510", "6935364070922", 1, 125.99,
        MAIN_NETWORK, "Access Point", "TP-Link",
        [
            "Tip: Xarici CPE (Point-to-Point / Point-to-Multipoint)",
            "Simsiz: 5 GHz, 300 Mbps",
            "Antena: Daxili 13 dBi (2×2 dual-polarized)",
            "Standart: IEEE 802.11a/n, Pharos MAXtream (TDMA)",
            "Port: 1× 10/100 Mbps (passiv PoE)",
            "Məsafə: 15 km-ə qədər",
            "Güc: Passiv PoE (16–27 VDC)",
            "Qoruma: IPX5, 15KV ESD, 6KV ildırımdan qorunma",
            "Rejimlər: AP / Client / Repeater / Bridge / AP Router / WISP",
            "Menecment: Pharos Control (mərkəzləşdirilmiş)",
            "Prosessor: Qualcomm Atheros 560 MHz",
        ],
        [
            "Тип: Наружная CPE (точка-точка / точка-многоточка)",
            "Беспроводная связь: 5 ГГц, 300 Мбит/с",
            "Антенна: Встроенная 13 дБи (2×2 с двойной поляризацией)",
            "Стандарт: IEEE 802.11a/n, Pharos MAXtream (TDMA)",
            "Порт: 1× 10/100 Мбит/с (пассивный PoE)",
            "Дальность: до 15 км",
            "Питание: Пассивный PoE (16–27 В DC)",
            "Защита: IPX5, защита от ЭСР 15 кВ, от молнии 6 кВ",
            "Режимы: AP / Client / Repeater / Bridge / AP Router / WISP",
            "Управление: Pharos Control (централизованное)",
            "Процессор: Qualcomm Atheros 560 МГц",
        ],
        [
            "Type: Outdoor CPE (Point-to-Point / Point-to-Multipoint)",
            "Wireless: 5 GHz, 300 Mbps",
            "Antenna: Built-in 13 dBi (2×2 dual-polarized)",
            "Standard: IEEE 802.11a/n, Pharos MAXtream (TDMA)",
            "Port: 1× 10/100 Mbps (passive PoE)",
            "Range: up to 15 km",
            "Power: Passive PoE (16–27 VDC)",
            "Protection: IPX5, 15KV ESD, 6KV lightning protection",
            "Modes: AP / Client / Repeater / Bridge / AP Router / WISP",
            "Management: Pharos Control (centralized)",
            "Processor: Qualcomm Atheros 560 MHz",
        ],
    ),
    (
        16, "TP-Link LS105GP UN", "4895252504545", 14, 70.99,
        MAIN_NETWORK, "Kommutator", "TP-Link",
        [
            "Tip: Kommutator (idarəolunmaz)",
            "Portlar: 5× 10/100/1000 Mbps (1–4 PoE+)",
            "PoE büdcəsi: 65 W (port başına 30 W-a qədər)",
            "PoE standartı: IEEE 802.3af/at",
            "Kommutasiya tutumu: 10 Gbps",
            "Extend Mode: 250 m-ə qədər (1–2 port)",
            "PoE Auto Recovery: Bəli",
            "MAC cədvəli: 2K",
            "Jumbo frame: 16 KB",
            "Korpus: Metal, fanless",
            "Ölçü: 99.8×98×25 mm",
        ],
        [
            "Тип: Коммутатор (неуправляемый)",
            "Порты: 5× 10/100/1000 Мбит/с (1–4 PoE+)",
            "PoE-бюджет: 65 Вт (до 30 Вт на порт)",
            "Стандарт PoE: IEEE 802.3af/at",
            "Коммутационная способность: 10 Гбит/с",
            "Extend Mode: до 250 м (порты 1–2)",
            "PoE Auto Recovery: Да",
            "MAC-таблица: 2K",
            "Jumbo frame: 16 КБ",
            "Корпус: Металлический, без вентилятора",
            "Размеры: 99.8×98×25 мм",
        ],
        [
            "Type: Switch (unmanaged)",
            "Ports: 5× 10/100/1000 Mbps (1–4 PoE+)",
            "PoE budget: 65 W (up to 30 W per port)",
            "PoE standard: IEEE 802.3af/at",
            "Switching capacity: 10 Gbps",
            "Extend Mode: up to 250 m (ports 1–2)",
            "PoE Auto Recovery: Yes",
            "MAC table: 2K",
            "Jumbo frame: 16 KB",
            "Casing: Metal, fanless",
            "Dimensions: 99.8×98×25 mm",
        ],
    ),
    (
        17, "TP-Link VIGI NVR1004H-4P", "4897098688748", 2, 184.99,
        MAIN_SECURITY, "NVR (Video registrator)", "TP-Link",
        [
            "Tip: Şəbəkə videoqeydiyyatçısı (NVR)",
            "Kanallar: 4 kanal IP video",
            "PoE portları: 4× 10/100 Mbps (PoE+), 53 W büdcə",
            "Video sıxlaşdırma: H.265+/H.265/H.264+/H.264",
            "Maks. qətnamə: 8 MP (qeyd)",
            "HDMI çıxış: 4K (3840×2160/30Hz)",
            "VGA çıxış: 1920×1080/60Hz",
            "Yaddaş: 1× SATA (10 TB-a qədər)",
            "USB: 2× USB 2.0",
            "Səs: 1× RCA giriş, 1× RCA çıxış",
            "ONVIF: Dəstəklənir (Profile S)",
            "Ölçü: 246.2×148.2×45 mm",
        ],
        [
            "Тип: Сетевой видеорегистратор (NVR)",
            "Каналы: 4 канала IP-видео",
            "PoE-порты: 4× 10/100 Мбит/с (PoE+), бюджет 53 Вт",
            "Сжатие видео: H.265+/H.265/H.264+/H.264",
            "Макс. разрешение: 8 Мп (запись)",
            "HDMI-выход: 4K (3840×2160/30 Гц)",
            "VGA-выход: 1920×1080/60 Гц",
            "Хранилище: 1× SATA (до 10 ТБ)",
            "USB: 2× USB 2.0",
            "Аудио: 1× RCA вход, 1× RCA выход",
            "ONVIF: Поддерживается (Profile S)",
            "Размеры: 246.2×148.2×45 мм",
        ],
        [
            "Type: Network Video Recorder (NVR)",
            "Channels: 4-channel IP video",
            "PoE ports: 4× 10/100 Mbps (PoE+), 53 W budget",
            "Video compression: H.265+/H.265/H.264+/H.264",
            "Max resolution: 8 MP (recording)",
            "HDMI output: 4K (3840×2160/30Hz)",
            "VGA output: 1920×1080/60Hz",
            "Storage: 1× SATA (up to 10 TB)",
            "USB: 2× USB 2.0",
            "Audio: 1× RCA input, 1× RCA output",
            "ONVIF: Supported (Profile S)",
            "Dimensions: 246.2×148.2×45 mm",
        ],
    ),
    (
        18, "TP-Link LS1210GP", "4895252504569", 1, 129.99,
        MAIN_NETWORK, "Kommutator", "TP-Link",
        [
            "Tip: Kommutator (idarəolunmaz)",
            "Portlar: 9× 10/100/1000 Mbps (1–8 PoE+) + 1× Gigabit SFP",
            "PoE büdcəsi: 61 W (port başına 30 W-a qədər)",
            "PoE standartı: IEEE 802.3af/at",
            "Kommutasiya tutumu: 20 Gbps",
            "Extend Mode: 250 m-ə qədər (1–4 port)",
            "Isolation Mode: Bəli (1–8 port)",
            "PoE Auto Recovery: Bəli",
            "MAC cədvəli: 4K",
            "Fan: Fanless (səssiz)",
            "Ölçü: 209×126×26 mm",
        ],
        [
            "Тип: Коммутатор (неуправляемый)",
            "Порты: 9× 10/100/1000 Мбит/с (1–8 PoE+) + 1× Gigabit SFP",
            "PoE-бюджет: 61 Вт (до 30 Вт на порт)",
            "Стандарт PoE: IEEE 802.3af/at",
            "Коммутационная способность: 20 Гбит/с",
            "Extend Mode: до 250 м (порты 1–4)",
            "Isolation Mode: Да (порты 1–8)",
            "PoE Auto Recovery: Да",
            "MAC-таблица: 4K",
            "Вентилятор: Нет (бесшумный)",
            "Размеры: 209×126×26 мм",
        ],
        [
            "Type: Switch (unmanaged)",
            "Ports: 9× 10/100/1000 Mbps (1–8 PoE+) + 1× Gigabit SFP",
            "PoE budget: 61 W (up to 30 W per port)",
            "PoE standard: IEEE 802.3af/at",
            "Switching capacity: 20 Gbps",
            "Extend Mode: up to 250 m (ports 1–4)",
            "Isolation Mode: Yes (ports 1–8)",
            "PoE Auto Recovery: Yes",
            "MAC table: 4K",
            "Fan: Fanless (silent)",
            "Dimensions: 209×126×26 mm",
        ],
    ),
    (
        19, "TP-Link EAP723", "8885020623031", 2, 364.99,
        MAIN_NETWORK, "Access Point", "TP-Link",
        [
            "Tip: Access Point (tavan, Wi-Fi 7)",
            "Wi-Fi sinfi: BE3600 (2882 Mbps 5 GHz + 688 Mbps 2.4 GHz, EU)",
            "Standart: IEEE 802.11 a/b/g/n/ac/ax/be",
            "Port: 1× 2.5G Ethernet",
            "Antenalar: 2× 4 dBi (2.4 GHz) + 2× 5 dBi (5 GHz)",
            "Kliyent tutumu: 250+ eyni vaxtda",
            "SSID: 16 (hər bantda 8)",
            "Güc: 802.3at PoE / 12V DC",
            "Mesh: Dəstəklənir",
            "Omada SDN: Mərkəzləşdirilmiş idarəetmə",
            "Maks. güc istehlakı: 16.8 W (PoE)",
            "Ölçü: 160×160×36.7 mm",
        ],
        [
            "Тип: Точка доступа (потолочная, Wi-Fi 7)",
            "Класс Wi-Fi: BE3600 (2882 Мбит/с 5 ГГц + 688 Мбит/с 2.4 ГГц, EU)",
            "Стандарт: IEEE 802.11 a/b/g/n/ac/ax/be",
            "Порт: 1× 2.5G Ethernet",
            "Антенны: 2× 4 дБи (2.4 ГГц) + 2× 5 дБи (5 ГГц)",
            "Емкость клиентов: 250+ одновременных",
            "SSID: 16 (по 8 на каждый диапазон)",
            "Питание: 802.3at PoE / 12V DC",
            "Mesh: Поддерживается",
            "Omada SDN: Централизованное управление",
            "Макс. потребление: 16.8 Вт (PoE)",
            "Размеры: 160×160×36.7 мм",
        ],
        [
            "Type: Access Point (ceiling, Wi-Fi 7)",
            "Wi-Fi class: BE3600 (2882 Mbps 5 GHz + 688 Mbps 2.4 GHz, EU)",
            "Standard: IEEE 802.11 a/b/g/n/ac/ax/be",
            "Port: 1× 2.5G Ethernet",
            "Antennas: 2× 4 dBi (2.4 GHz) + 2× 5 dBi (5 GHz)",
            "Client capacity: 250+ concurrent",
            "SSID: 16 (8 per band)",
            "Power: 802.3at PoE / 12V DC",
            "Mesh: Supported",
            "Omada SDN: Centralized management",
            "Max power consumption: 16.8 W (PoE)",
            "Dimensions: 160×160×36.7 mm",
        ],
    ),
    (
        20, "TP-Link TL-SL1311P", "4895252500288", 1, 94.99,
        MAIN_NETWORK, "Kommutator", "TP-Link",
        [
            "Tip: Kommutator (idarəolunmaz)",
            "Portlar: 8× 10/100 Mbps PoE+ + 2× Gigabit RJ45 + 1× Gigabit SFP",
            "PoE büdcəsi: 65 W (port başına 30 W-a qədər)",
            "PoE standartı: IEEE 802.3af/at",
            "Kommutasiya tutumu: 7.6 Gbps",
            "Extend Mode: 250 m-ə qədər",
            "Isolation Mode: Bəli",
            "PoE Auto Recovery: Bəli",
            "MAC cədvəli: 2K",
            "Fan: Fanless (səssiz)",
            "Ölçü: 209×126×26 mm",
        ],
        [
            "Тип: Коммутатор (неуправляемый)",
            "Порты: 8× 10/100 Мбит/с PoE+ + 2× Gigabit RJ45 + 1× Gigabit SFP",
            "PoE-бюджет: 65 Вт (до 30 Вт на порт)",
            "Стандарт PoE: IEEE 802.3af/at",
            "Коммутационная способность: 7.6 Гбит/с",
            "Extend Mode: до 250 м",
            "Isolation Mode: Да",
            "PoE Auto Recovery: Да",
            "MAC-таблица: 2K",
            "Вентилятор: Нет (бесшумный)",
            "Размеры: 209×126×26 мм",
        ],
        [
            "Type: Switch (unmanaged)",
            "Ports: 8× 10/100 Mbps PoE+ + 2× Gigabit RJ45 + 1× Gigabit SFP",
            "PoE budget: 65 W (up to 30 W per port)",
            "PoE standard: IEEE 802.3af/at",
            "Switching capacity: 7.6 Gbps",
            "Extend Mode: up to 250 m",
            "Isolation Mode: Yes",
            "PoE Auto Recovery: Yes",
            "MAC table: 2K",
            "Fan: Fanless (silent)",
            "Dimensions: 209×126×26 mm",
        ],
    ),
    (
        21, "TP-Link VIGI POE+ NVR1008H-8MP", "4897098688762", 1, 220.99,
        MAIN_SECURITY, "NVR (Video registrator)", "TP-Link",
        [
            "Tip: Şəbəkə videoqeydiyyatçısı (NVR)",
            "Kanallar: 8 kanal IP video",
            "PoE portları: 8× 10/100 Mbps (PoE+), 113 W büdcə",
            "Video sıxlaşdırma: H.265+/H.265/H.264+/H.264",
            "Maks. qətnamə: 8 MP (qeyd)",
            "HDMI çıxış: 4K (3840×2160/30Hz)",
            "VGA çıxış: 1920×1080/60Hz",
            "Yaddaş: 1× SATA (16 TB-a qədər)",
            "USB: 2× USB 2.0",
            "Səs: 1× RCA giriş, 1× RCA çıxış",
            "ONVIF: Dəstəklənir (Profile S/T)",
            "Güc: 53.5V DC / 2.43A",
        ],
        [
            "Тип: Сетевой видеорегистратор (NVR)",
            "Каналы: 8 каналов IP-видео",
            "PoE-порты: 8× 10/100 Мбит/с (PoE+), бюджет 113 Вт",
            "Сжатие видео: H.265+/H.265/H.264+/H.264",
            "Макс. разрешение: 8 Мп (запись)",
            "HDMI-выход: 4K (3840×2160/30 Гц)",
            "VGA-выход: 1920×1080/60 Гц",
            "Хранилище: 1× SATA (до 16 ТБ)",
            "USB: 2× USB 2.0",
            "Аудио: 1× RCA вход, 1× RCA выход",
            "ONVIF: Поддерживается (Profile S/T)",
            "Питание: 53.5V DC / 2.43A",
        ],
        [
            "Type: Network Video Recorder (NVR)",
            "Channels: 8-channel IP video",
            "PoE ports: 8× 10/100 Mbps (PoE+), 113 W budget",
            "Video compression: H.265+/H.265/H.264+/H.264",
            "Max resolution: 8 MP (recording)",
            "HDMI output: 4K (3840×2160/30Hz)",
            "VGA output: 1920×1080/60Hz",
            "Storage: 1× SATA (up to 16 TB)",
            "USB: 2× USB 2.0",
            "Audio: 1× RCA input, 1× RCA output",
            "ONVIF: Supported (Profile S/T)",
            "Power: 53.5V DC / 2.43A",
        ],
    ),
]

HEADERS = [
    ("№", 6),
    ("Model", 26),
    ("Barkod", 16),
    ("Qty", 6),
    ("Qiymət (AZN) — endirimli", 18),
    ("Köhnə qiymət (AZN)", 18),
    ("Əsas kateqoriya", 26),
    ("Alt kateqoriya", 24),
    ("Brend", 12),
    ("Xüsusiyyətlər (AZ)", 42),
    ("Xüsusiyyətlər (RU)", 42),
    ("Xüsusiyyətlər (EN)", 42),
    ("Şəkil linkləri", 40),
]

CATEGORY_SHEET = [
    ("Təhlükəsizlik avadanlıqları", "tehlukesizlik-avadanliqlari", "IP kamera", "ip-kamera", "Mövcud"),
    ("Təhlükəsizlik avadanlıqları", "tehlukesizlik-avadanliqlari", "Wi-Fi kameralar", "wi-fi-kameralar", "Mövcud"),
    ("Təhlükəsizlik avadanlıqları", "tehlukesizlik-avadanliqlari", "NVR (Video registrator)", "nvr", "YENİ — yaradılmalıdır"),
    ("Şəbəkə avadanlıqları", "sebeke-avadanliqlari", "Router", "router", "Mövcud"),
    ("Şəbəkə avadanlıqları", "sebeke-avadanliqlari", "Kommutator", "kommutator", "Mövcud"),
    ("Şəbəkə avadanlıqları", "sebeke-avadanliqlari", "Access Point", "access-point", "Mövcud"),
    ("Şəbəkə avadanlıqları", "sebeke-avadanliqlari", "Wi-Fi gücləndirici", "wi-fi-guclendirici", "Mövcud"),
]


def build_wb():
    wb = Workbook()

    thin = Side(style="thin", color="D0D0D0")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    title_font = Font(name="Calibri", size=14, bold=True, color="1F4E79")
    wrap = Alignment(vertical="top", wrap_text=True)
    center = Alignment(horizontal="center", vertical="top", wrap_text=True)

    # ---------- Sheet 1: Məhsullar ----------
    ws = wb.active
    ws.title = "Məhsullar"

    ws["A1"] = "Konnektronik — Məhsul siyahısı (13.08.2026) | IT Market üçün"
    ws["A1"].font = title_font
    ws["A2"] = ("Qiymət (AZN) — hazırkı endirimli qiymətdir və dəyişmir. Köhnə qiymət = Qiymət + 20 AZN. "
                "RU və EN xüsusiyyətlər lüğət bazasına əlavə olunmaq üçündür.")
    ws["A2"].font = Font(name="Calibri", size=10, italic=True, color="555555")

    header_row = 3
    for col, (name, width) in enumerate(HEADERS, start=1):
        cell = ws.cell(row=header_row, column=col, value=name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
        cell.border = border
        ws.column_dimensions[get_column_letter(col)].width = width

    row = header_row + 1
    for num, model, barcode, qty, price, main, sub, brand, az, ru, en in PRODUCTS:
        old_price = round(price + 20, 2)
        values = [
            num, model, barcode, qty, price, old_price,
            main, sub, brand,
            "\n".join(az), "\n".join(ru), "\n".join(en), "",
        ]
        for col, v in enumerate(values, start=1):
            cell = ws.cell(row=row, column=col, value=v)
            cell.border = border
            cell.alignment = center if col in (1, 4, 5, 6) else wrap
        row += 1

    ws.freeze_panes = "B4"
    ws.auto_filter.ref = f"A{header_row}:{get_column_letter(len(HEADERS))}{row - 1}"

    # ---------- Sheet 2: Kateqoriyalar ----------
    ws2 = wb.create_sheet("Kateqoriyalar")
    ws2["A1"] = "Saytda mövcud və yeni təklif olunan kateqoriyalar"
    ws2["A1"].font = title_font

    cat_headers = ["Əsas kateqoriya", "Əsas slug", "Alt kateqoriya", "Alt slug", "Status"]
    for col, name in enumerate(cat_headers, start=1):
        cell = ws2.cell(row=3, column=col, value=name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
        cell.border = border
        ws2.column_dimensions[get_column_letter(col)].width = 34

    for r, (main, main_slug, sub, sub_slug, status) in enumerate(CATEGORY_SHEET, start=4):
        for c, v in enumerate([main, main_slug, sub, sub_slug, status], start=1):
            cell = ws2.cell(row=r, column=c, value=v)
            cell.border = border
            cell.alignment = wrap
            if status.startswith("YENİ"):
                cell.fill = PatternFill("solid", fgColor="FFF2CC")
                cell.font = Font(bold=True, color="7F6000")

    ws2.freeze_panes = "A4"

    out = "Sayt üçün 13082026_260812_162518 -Konnektronik.xlsx"
    wb.save(out)
    print(f"OK: {out} ({len(PRODUCTS)} products, {row - 1 - header_row} rows)")


if __name__ == "__main__":
    build_wb()
