-- AlterTable
ALTER TABLE "brands" ADD COLUMN "logo_scale_percent" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "logo_offset_x" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "logo_offset_y" INTEGER NOT NULL DEFAULT 0;
